## Contents

- [Querying Nominatim for Coordinates from Place Names](#querying-nominatim-for-coordinates-from-place-names)
- [Querying OpenWeatherMap for Weather from Coordinates](#querying-openweathermap-for-weather-from-coordinates)
- [Scraping Booking.com](#scraping-bookingcom)
- [Making the Final Visualisations](#making-the-final-visualisations)
- [Loading the CSV Into an S3 Bucket](#loading-the-csv-into-an-s3-bucket)

In [34]:
import requests, os, json, boto3

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

from tqdm import tqdm
from time import sleep
from random import randint
from scrapy import Selector
from dotenv import load_dotenv
from plotly.subplots import make_subplots

## Querying Nominatim for Coordinates from Place Names

In [ ]:
load_dotenv()

def get_coords(place_name):
    url = "https://nominatim.openstreetmap.org/search"
    params = {
        "q": place_name,
        "format": "json",
        "limit": 1
    }
    headers = {
        "User-Agent": f"ExamAssignment/1.0 ({os.environ["NOMINATIM_EMAIL"]})"
    }
    
    try:
        response = requests.get(url, params=params, headers=headers)
        response.raise_for_status()
        data = response.json()
    except Exception as e:
        return e
    
    if data:
        lat = data[0]["lat"]
        lon = data[0]["lon"]
        return {"lat" : float(lat), "lon" : float(lon)}
    else:
        print("No results found.")
        return None

destination_list = ["Mont Saint Michel", "St Malo", "Bayeux", "Le Havre", "Rouen", "Paris", "Amiens", "Lille", "Strasbourg", "Chateau du Haut Koenigsbourg", "Colmar", "Eguisheim",
                    "Besancon", "Dijon", "Annecy", "Grenoble", "Lyon", "Gorges du Verdon", "Bormes les Mimosas", "Cassis", "Marseille", "Aix en Provence", "Avignon", "Uzes", "Nimes",
                    "Aigues Mortes", "Saintes Maries de la mer", "Collioure", "Carcassonne", "Ariege", "Toulouse", "Montauban", "Biarritz", "Bayonne", "La Rochelle"]

coords_dict = dict()

for destination in destination_list:
    coords_dict[destination] = get_coords(destination)
    sleep(5)

coords_dict

{'Mont Saint Michel': {'lat': 48.6359541, 'lon': -1.51146},
 'St Malo': {'lat': 49.314695, 'lon': -96.9538228},
 'Bayeux': {'lat': 49.2764624, 'lon': -0.7024738},
 'Le Havre': {'lat': 49.4938975, 'lon': 0.1079732},
 'Rouen': {'lat': 49.4404591, 'lon': 1.0939658},
 'Paris': {'lat': 48.8534951, 'lon': 2.3483915},
 'Amiens': {'lat': 49.8941708, 'lon': 2.2956951},
 'Lille': {'lat': 50.6365654, 'lon': 3.0635282},
 'Strasbourg': {'lat': 48.584614, 'lon': 7.7507127},
 'Chateau du Haut Koenigsbourg': {'lat': 48.2494107, 'lon': 7.3443202},
 'Colmar': {'lat': 48.0777517, 'lon': 7.3579641},
 'Eguisheim': {'lat': 48.0447968, 'lon': 7.3079618},
 'Besancon': {'lat': 47.2380222, 'lon': 6.0243622},
 'Dijon': {'lat': 47.3215806, 'lon': 5.0414701},
 'Annecy': {'lat': 45.8992348, 'lon': 6.1288847},
 'Grenoble': {'lat': 45.1875602, 'lon': 5.7357819},
 'Lyon': {'lat': 45.7578137, 'lon': 4.8320114},
 'Gorges du Verdon': {'lat': 43.7496562, 'lon': 6.3285616},
 'Bormes les Mimosas': {'lat': 43.1506968, 'lon': 6.3419285},
 'Cassis': {'lat': 43.2140359, 'lon': 5.5396318},
 'Marseille': {'lat': 43.2961743, 'lon': 5.3699525},
 'Aix en Provence': {'lat': 43.5298424, 'lon': 5.4474738},
 'Avignon': {'lat': 43.9492493, 'lon': 4.8059012},
 'Uzes': {'lat': 44.0121279, 'lon': 4.4196718},
 'Nimes': {'lat': 43.8374249, 'lon': 4.3600687},
 'Aigues Mortes': {'lat': 43.5661521, 'lon': 4.19154},
 'Saintes Maries de la mer': {'lat': 43.4515922, 'lon': 4.4277202},
 'Collioure': {'lat': 42.52505, 'lon': 3.0831554},
 'Carcassonne': {'lat': 43.2130358, 'lon': 2.3491069},
 'Ariege': {'lat': 42.9455368, 'lon': 1.4065544},
 'Toulouse': {'lat': 43.6044638, 'lon': 1.4442433},
 'Montauban': {'lat': 44.0175835, 'lon': 1.3549991},
 'Biarritz': {'lat': 43.4832523, 'lon': -1.5592776},
 'Bayonne': {'lat': 43.4945144, 'lon': -1.4736657},
 'La Rochelle': {'lat': 46.159732, 'lon': -1.1515951}}

## Querying OpenWeatherMap for Weather from Coordinates

In [ ]:
load_dotenv()

def get_weather(coords_as_dict: dict):
    url = "https://api.openweathermap.org/data/3.0/onecall"
    params = {
        "lat" : coords_as_dict["lat"],
        "lon" : coords_as_dict["lon"],
        "APPID" : os.environ["OPENWEATHER_API_KEY"],
        "units" : "metric",
        "exclude" : "current,minutely,hourly,alerts"
    }
    
    try:
        response = requests.get(url, params=params)
        response.raise_for_status()
        data = response.json()
    except Exception as e:
        return e
    
    if data:
        return data["daily"]
    else:
        print("No results found.")
        return None

weather_dict = coords_dict.copy()

for destination, coords in tqdm(weather_dict.items()):
    weather_dict[destination]["daily_forecast"] = get_weather(coords)
    sleep(5)

weather_dict

100%|██████████| 35/35 [02:59<00:00,  5.13s/it]

{'Mont Saint Michel': {'lat': 48.6359541,
  'lon': -1.51146,
  'daily_forecast': [{'dt': 1760526000,
    'sunrise': 1760509557,
    'sunset': 1760548639,
    'moonrise': 1760484300,
    'moonset': 1760541300,
    'moon_phase': 0.81,
    'summary': 'The day will start with partly cloudy through the late morning hours, transitioning to clearing',
    'temp': {'day': 17.03,
     'min': 11.25,
     'max': 17.52,
     'night': 12.15,
     'eve': 15.7,
     'morn': 11.48},
    'feels_like': {'day': 16.43, 'night': 11.54, 'eve': 15.13, 'morn': 10.69},
    'pressure': 1026,
    'humidity': 63,
    'dew_point': 6.78,
    'wind_speed': 5.91,
    'wind_deg': 46,
    'wind_gust': 10.82,
    'weather': [{'id': 800,
      'main': 'Clear',
      'description': 'clear sky',
      'icon': '01d'}],
    'clouds': 0,
    'pop': 0,
    'uvi': 2.68},
   {'dt': 1760612400,
    'sunrise': 1760596048,
    'sunset': 1760634922,
    'moonrise': 1760575380,
    'moonset': 1760628780,
    'moon_phase': 0.84,
    'summary': 'There will be clear sky today',
    'temp': {'day': 17.54,
     'min': 9.35,
     'max': 19.56,
     'night': 10.45,
     'eve': 15.73,
     'morn': 9.61},
    'feels_like': {'day': 16.76, 'night': 9.54, 'eve': 14.9, 'morn': 7.46},
    'pressure': 1024,
    'humidity': 54,
    'dew_point': 7.83,
    'wind_speed': 6.39,
    'wind_deg': 77,
    'wind_gust': 10.71,
    'weather': [{'id': 800,
      'main': 'Clear',
      'description': 'clear sky',
      'icon': '01d'}],
    'clouds': 6,
    'pop': 0,
    'uvi': 2.5},
   {'dt': 1760698800,
    'sunrise': 1760682539,
    'sunset': 1760721206,
    'moonrise': 1760666280,
    'moonset': 1760716080,
    'moon_phase': 0.87,
    'summary': 'You can expect clear sky in the morning, with partly cloudy in the afternoon',
    'temp': {'day': 17.21,
     'min': 7.74,
     'max': 19.28,
     'night': 10.84,
     'eve': 15.19,
     'morn': 7.9},
    'feels_like': {'day': 16.19, 'night': 9.73, 'eve': 14.12, 'morn': 5.59},
    'pressure': 1023,
    'humidity': 46,
    'dew_point': 5.22,
    'wind_speed': 6.45,
    'wind_deg': 93,
    'wind_gust': 10.79,
    'weather': [{'id': 800,
      'main': 'Clear',
      'description': 'clear sky',
      'icon': '01d'}],
    'clouds': 9,
    'pop': 0,
    'uvi': 2.42},
   {'dt': 1760785200,
    'sunrise': 1760769030,
    'sunset': 1760807491,
    'moonrise': 1760756940,
    'moonset': 1760803260,
    'moon_phase': 0.9,
    'summary': 'There will be partly cloudy today',
    'temp': {'day': 16.82,
     'min': 7.58,
     'max': 19.32,
     'night': 11.47,
     'eve': 15.39,
     'morn': 7.83},
    'feels_like': {'day': 15.78, 'night': 10.21, 'eve': 14.24, 'morn': 5.19},
    'pressure': 1021,
    'humidity': 47,
    'dew_point': 5.14,
    'wind_speed': 6.82,
    'wind_deg': 121,
    'wind_gust': 12.08,
    'weather': [{'id': 804,
      'main': 'Clouds',
      'description': 'overcast clouds',
      'icon': '04d'}],
    'clouds': 90,
    'pop': 0,
    'uvi': 2.16},
   {'dt': 1760871600,
    'sunrise': 1760855522,
    'sunset': 1760893777,
    'moonrise': 1760847540,
    'moonset': 1760890440,
    'moon_phase': 0.94,
    'summary': 'You can expect partly cloudy in the morning, with rain in the afternoon',
    'temp': {'day': 20.03,
     'min': 9.7,
     'max': 20.32,
     'night': 15.95,
     'eve': 16.6,
     'morn': 10.3},
    'feels_like': {'day': 19.37, 'night': 16.08, 'eve': 16.56, 'morn': 9.27},
    'pressure': 1009,
    'humidity': 49,
    'dew_point': 8.85,
    'wind_speed': 7.95,
    'wind_deg': 182,
    'wind_gust': 14.66,
    'weather': [{'id': 500,
      'main': 'Rain',
      'description': 'light rain',
      'icon': '10d'}],
    'clouds': 100,
    'pop': 1,
    'rain': 1.68,
    'uvi': 1.85},
   {'dt': 1760958000,
    'sunrise': 1760942014,
    'sunset': 1760980065,
    'moonrise': 1760938080,
    'moonset': 1760977620,
    'moon_phase': 0.97,
    'summary': 'Expect a day of partly cloudy with rain',
    'temp': {'day': 18.03,
     'min': 12.08,
     'max': 18.05,
     'night': 12.08,
     'eve': 15.36,
     'morn': 13.43},
    'feels_like': {'day': 17.35, 'night': 11.67, 'eve': 14.65, 'morn': 13.18},
    'pressure': 1004,
    'humidity': 56,
    'dew_point': 9,
    'wind_speed': 7.11,
    'wind_deg': 250,
    'wind_gust': 11.57,
    'weather': [{'id': 500,
      'main': 'Rain',
      'description': 'light rain',
      'icon': '10d'}],
    'clouds': 11,
    'pop': 1,
    'rain': 1.08,
    'uvi': 2},
   {'dt': 1761044400,
    'sunrise': 1761028507,
    'sunset': 1761066353,
    'moonrise': 1761028560,
    'moonset': 1761064860,
    'moon_phase': 0,
    'summary': 'Expect a day of partly cloudy with rain',
    'temp': {'day': 14.75,
     'min': 11.72,
     'max': 15.3,
     'night': 11.72,
     'eve': 13.35,
     'morn': 12.45},
    'feels_like': {'day': 14.47, 'night': 11.32, 'eve': 12.96, 'morn': 12.23},
    'pressure': 1000,
    'humidity': 84,
    'dew_point': 11.81,
    'wind_speed': 7.3,
    'wind_deg': 296,
    'wind_gust': 11.43,
    'weather': [{'id': 501,
      'main': 'Rain',
      'description': 'moderate rain',
      'icon': '10d'}],
    'clouds': 99,
    'pop': 1,
    'rain': 11.76,
    'uvi': 2},
   {'dt': 1761130800,
    'sunrise': 1761115000,
    'sunset': 1761152642,
    'moonrise': 1761119160,
    'moonset': 1761152340,
    'moon_phase': 0.03,
    'summary': 'The day will start with partly cloudy through the late morning hours, transitioning to rain',
    'temp': {'day': 14.98,
     'min': 10.18,
     'max': 17.31,
     'night': 16.84,
     'eve': 16.87,
     'morn': 10.24},
    'feels_like': {'day': 14.99, 'night': 17.06, 'eve': 17.07, 'morn': 9.75},
    'pressure': 1006,
    'humidity': 94,
    'dew_point': 13.85,
    'wind_speed': 8.5,
    'wind_deg': 182,
    'wind_gust': 16.05,
    'weather': [{'id': 500,
      'main': 'Rain',
      'description': 'light rain',
      'icon': '10d'}],
    'clouds': 100,
    'pop': 1,
    'rain': 5.04,
    'uvi': 2}]},
 'St Malo': {'lat': 49.314695,
  'lon': -96.9538228,
  'daily_forecast': [{'dt': 1760551200,
    'sunrise': 1760532541,
    'sunset': 1760571460,
    'moonrise': 1760508300,
    'moonset': 1760564640,
    'moon_phase': 0.82,
    'summary': 'You can expect partly cloudy in the morning, with clearing in the afternoon',
    'temp': {'day': 8.82,
     'min': 5.46,
     'max': 10.45,
     'night': 7.93,
     'eve': 8.68,
     'morn': 5.68},
    'feels_like': {'day': 6.72, 'night': 5.55, 'eve': 6.76, 'morn': 4.02},
    'pressure': 1025,
    'humidity': 79,
    'dew_point': 5.38,
    'wind_speed': 3.83,
    'wind_deg': 125,
    'wind_gust': 10.18,
    'weather': [{'id': 804,
      'main': 'Clouds',
      'description': 'overcast clouds',
      'icon': '04d'}],
    'clouds': 100,
    'pop': 0,
    'uvi': 2.31},
   {'dt': 1760637600,
    'sunrise': 1760619035,
    'sunset': 1760657741,
    'moonrise': 1760599380,
    'moonset': 1760652000,
    'moon_phase': 0.85,
    'summary': 'Expect a day of partly cloudy with rain',
    'temp': {'day': 11.03,
     'min': 7.99,
     'max': 14.61,
     'night': 14.61,
     'eve': 13.55,
     'morn': 10.33},
    'feels_like': {'day': 10.62, 'night': 14.48, 'eve': 13.47, 'morn': 9.79},
    'pressure': 1010,
    'humidity': 93,
    'dew_point': 9.91,
    'wind_speed': 5.47,
    'wind_deg': 112,
    'wind_gust': 12.61,
    'weather': [{'id': 501,
      'main': 'Rain',
      'description': 'moderate rain',
      'icon': '10d'}],
    'clouds': 100,
    'pop': 1,
    'rain': 10.51,
    'uvi': 0.58},
   {'dt': 1760724000,
    'sunrise': 1760705529,
    'sunset': 1760744023,
    'moonrise': 1760690280,
    'moonset': 1760739240,
    'moon_phase': 0.88,
    'summary': 'Expect a day of partly cloudy with rain',
    'temp': {'day': 12.51,
     'min': 9.67,
     'max': 16.25,
     'night': 9.67,
     'eve': 12.21,
     'morn': 12.26},
    'feels_like': {'day': 11.96, 'night': 7.96, 'eve': 11.58, 'morn': 11.87},
    'pressure': 990,
    'humidity': 82,
    'dew_point': 9.57,
    'wind_speed': 10.57,
    'wind_deg': 240,
    'wind_gust': 17.3,
    'weather': [{'id': 501,
      'main': 'Rain',
      'description': 'moderate rain',
      'icon': '10d'}],
    'clouds': 97,
    'pop': 1,
    'rain': 5.21,
    'uvi': 2.04},
   {'dt': 1760810400,
    'sunrise': 1760792023,
    'sunset': 1760830305,
    'moonrise': 1760780940,
    'moonset': 1760826420,
    'moon_phase': 0.91,
    'summary': 'Expect a day of partly cloudy with clear spells',
    'temp': {'day': 12.88,
     'min': 5.98,
     'max': 13.58,
     'night': 7.52,
     'eve': 9.94,
     'morn': 6.3},
    'feels_like': {'day': 11.37, 'night': 5.15, 'eve': 7.6, 'morn': 3.86},
    'pressure': 1005,
    'humidity': 44,
    'dew_point': 0.96,
    'wind_speed': 6.88,
    'wind_deg': 279,
    'wind_gust': 10.89,
    'weather': [{'id': 800,
      'main': 'Clear',
      'description': 'clear sky',
      'icon': '01d'}],
    'clouds': 1,
    'pop': 0,
    'uvi': 1.49},
   {'dt': 1760896800,
    'sunrise': 1760878517,
    'sunset': 1760916589,
    'moonrise': 1760871540,
    'moonset': 1760913540,
    'moon_phase': 0.94,
    'summary': 'The day will start with partly cloudy through the late morning hours, transitioning to clearing',
    'temp': {'day': 9.5,
     'min': 4.19,
     'max': 10.45,
     'night': 5.44,
     'eve': 6.79,
     'morn': 4.19},
    'feels_like': {'day': 6.46, 'night': 3.63, 'eve': 4.74, 'morn': 1.4},
    'pressure': 1011,
    'humidity': 55,
    'dew_point': 0.77,
    'wind_speed': 6.47,
    'wind_deg': 311,
    'wind_gust': 13.06,
    'weather': [{'id': 800,
      'main': 'Clear',
      'description': 'clear sky',
      'icon': '01d'}],
    'clouds': 6,
    'pop': 0,
    'uvi': 2},
   {'dt': 1760983200,
    'sunrise': 1760965012,
    'sunset': 1761002874,
    'moonrise': 1760962080,
    'moonset': 1761000660,
    'moon_phase': 0.98,
    'summary': 'There will be clear sky today',
    'temp': {'day': 10.25,
     'min': 2.53,
     'max': 12.23,
     'night': 6.9,
     'eve': 8.2,
     'morn': 2.53},
    'feels_like': {'day': 8.56, 'night': 3.54, 'eve': 5.82, 'morn': 2.53},
    'pressure': 1014,
    'humidity': 47,
    'dew_point': -0.49,
    'wind_speed': 5.4,
    'wind_deg': 120,
    'wind_gust': 12.44,
    'weather': [{'id': 800,
      'main': 'Clear',
      'description': 'clear sky',
      'icon': '01d'}],
    'clouds': 0,
    'pop': 0,
    'uvi': 2},
   {'dt': 1761069600,
    'sunrise': 1761051507,
    'sunset': 1761089160,
    'moonrise': 1761052680,
    'moonset': 1761087960,
    'moon_phase': 0,
    'summary': 'There will be clear sky until morning, then partly cloudy',
    'temp': {'day': 11.62,
     'min': 6.6,
     'max': 11.62,
     'night': 8.18,
     'eve': 9.1,
     'morn': 6.6},
    'feels_like': {'day': 10.14, 'night': 5.05, 'eve': 6.77, 'morn': 3.4},
    'pressure': 1005,
    'humidity': 50,
    'dew_point': 1.4,
    'wind_speed': 5.72,
    'wind_deg': 125,
    'wind_gust': 13.34,
    'weather': [{'id': 804,
      'main': 'Clouds',
      'description': 'overcast clouds',
      'icon': '04d'}],
    'clouds': 98,
    'pop': 0,
    'uvi': 2},
   {'dt': 1761156000,
    'sunrise': 1761138003,
    'sunset': 1761175447,
    'moonrise': 1761143340,
    'moonset': 1761175380,
    'moon_phase': 0.04,
    'summary': 'Expect a day of partly cloudy with clear spells',
    'temp': {'day': 11.01,
     'min': 3.75,
     'max': 12.62,
     'night': 8.31,
     'eve': 9.34,
     'morn': 3.75},
    'feels_like': {'day': 9.42, 'night': 7.3, 'eve': 8.8, 'morn': 1.07},
    'pressure': 1015,
    'humidity': 48,
    'dew_point': 0.52,
    'wind_speed': 5.28,
    'wind_deg': 336,
    'wind_gust': 12.82,
    'weather': [{'id': 800,
      'main': 'Clear',
      'description': 'clear sky',
      'icon': '01d'}],
    'clouds': 2,
    'pop': 0,
    'uvi': 2}]},
 'Bayeux': {'lat': 49.2764624,
  'lon': -0.7024738,
  'daily_forecast': [{'dt': 1760526000,
    'sunrise': 1760509413,
    'sunset': 1760548395,
    'moonrise': 1760483940,
    'moonset': 1760541240,
    'moon_phase': 0.81,
    'summary': 'There will be partly cloudy today',
    'temp': {'day': 13.92,
     'min': 11.35,
     'max': 16.14,
     'night': 12.63,
     'eve': 16.14,
     'morn': 11.73},
    'feels_like': {'day': 13.14, 'night': 11.96, 'eve': 15.82, 'morn': 11.2},
    'pressure': 1027,
    'humidity': 68,
    'dew_point': 7.8,
    'wind_speed': 6.83,
    'wind_deg': 73,
    'wind_gust': 9.57,
    'weather': [{'id': 803,
      'main': 'Clouds',
      'description': 'broken clouds',
      'icon': '04d'}],
    'clouds': 83,
    'pop': 0.2,
    'uvi': 1.65},
   {'dt': 1760612400,
    'sunrise': 1760595906,
    'sunset': 1760634675,
    'moonrise': 1760575080,
    'moonset': 1760628660,
    'moon_phase': 0.84,
    'summary': 'You can expect partly cloudy in the morning, with clearing in the afternoon',
    'temp': {'day': 15.84,
     'min': 9.19,
     'max': 16.57,
     'night': 11.92,
     'eve': 13.65,
     'morn': 9.19},
    'feels_like': {'day': 14.97, 'night': 11.15, 'eve': 12.98, 'morn': 7.42},
    'pressure': 1025,
    'humidity': 57,
    'dew_point': 7.45,
    'wind_speed': 6.44,
    'wind_deg': 62,
    'wind_gust': 11.21,
    'weather': [{'id': 804,
      'main': 'Clouds',
      'description': 'overcast clouds',
      'icon': '04d'}],
    'clouds': 95,
    'pop': 0,
    'uvi': 2.38},
   {'dt': 1760698800,
    'sunrise': 1760682400,
    'sunset': 1760720957,
    'moonrise': 1760665980,
    'moonset': 1760715960,
    'moon_phase': 0.87,
    'summary': 'The day will start with clear sky through the late morning hours, transitioning to partly cloudy',
    'temp': {'day': 16.65,
     'min': 7.71,
     'max': 18.06,
     'night': 10.28,
     'eve': 14.01,
     'morn': 7.74},
    'feels_like': {'day': 15.62, 'night': 9.32, 'eve': 13.4, 'morn': 5.59},
    'pressure': 1024,
    'humidity': 48,
    'dew_point': 5.67,
    'wind_speed': 6.34,
    'wind_deg': 85,
    'wind_gust': 10.48,
    'weather': [{'id': 801,
      'main': 'Clouds',
      'description': 'few clouds',
      'icon': '02d'}],
    'clouds': 17,
    'pop': 0,
    'uvi': 2.32},
   {'dt': 1760785200,
    'sunrise': 1760768894,
    'sunset': 1760807240,
    'moonrise': 1760756700,
    'moonset': 1760803080,
    'moon_phase': 0.9,
    'summary': 'There will be partly cloudy today',
    'temp': {'day': 16.07,
     'min': 6.45,
     'max': 18.46,
     'night': 10.13,
     'eve': 13.88,
     'morn': 6.74},
    'feels_like': {'day': 14.96, 'night': 8.82, 'eve': 12.63, 'morn': 3.92},
    'pressure': 1023,
    'humidity': 47,
    'dew_point': 4.69,
    'wind_speed': 6.28,
    'wind_deg': 113,
    'wind_gust': 10.95,
    'weather': [{'id': 804,
      'main': 'Clouds',
      'description': 'overcast clouds',
      'icon': '04d'}],
    'clouds': 92,
    'pop': 0,
    'uvi': 2.21},
   {'dt': 1760871600,
    'sunrise': 1760855388,
    'sunset': 1760893523,
    'moonrise': 1760847300,
    'moonset': 1760890200,
    'moon_phase': 0.94,
    'summary': 'You can expect partly cloudy in the morning, with rain in the afternoon',
    'temp': {'day': 17.87,
     'min': 9.15,
     'max': 19.51,
     'night': 15.84,
     'eve': 19.51,
     'morn': 10.38},
    'feels_like': {'day': 17.02, 'night': 15.75, 'eve': 18.95, 'morn': 9.22},
    'pressure': 1010,
    'humidity': 50,
    'dew_point': 7.42,
    'wind_speed': 7.22,
    'wind_deg': 204,
    'wind_gust': 14.27,
    'weather': [{'id': 500,
      'main': 'Rain',
      'description': 'light rain',
      'icon': '10d'}],
    'clouds': 100,
    'pop': 1,
    'rain': 0.77,
    'uvi': 1.84},
   {'dt': 1760958000,
    'sunrise': 1760941883,
    'sunset': 1760979808,
    'moonrise': 1760937900,
    'moonset': 1760977320,
    'moon_phase': 0.97,
    'summary': 'Expect a day of partly cloudy with rain',
    'temp': {'day': 16.19,
     'min': 10.68,
     'max': 17.23,
     'night': 10.68,
     'eve': 12.93,
     'morn': 13.11},
    'feels_like': {'day': 15.51, 'night': 10.15, 'eve': 12.39, 'morn': 12.8},
    'pressure': 1003,
    'humidity': 63,
    'dew_point': 9.04,
    'wind_speed': 8.49,
    'wind_deg': 242,
    'wind_gust': 12.67,
    'weather': [{'id': 500,
      'main': 'Rain',
      'description': 'light rain',
      'icon': '10d'}],
    'clouds': 93,
    'pop': 1,
    'rain': 0.85,
    'uvi': 2},
   {'dt': 1761044400,
    'sunrise': 1761028378,
    'sunset': 1761066094,
    'moonrise': 1761028440,
    'moonset': 1761064560,
    'moon_phase': 0,
    'summary': 'You can expect partly cloudy in the morning, with clearing in the afternoon',
    'temp': {'day': 16.35,
     'min': 11.04,
     'max': 16.41,
     'night': 11.04,
     'eve': 12.06,
     'morn': 12.45},
    'feels_like': {'day': 15.74, 'night': 10.63, 'eve': 11.67, 'morn': 11.94},
    'pressure': 999,
    'humidity': 65,
    'dew_point': 9.75,
    'wind_speed': 7.18,
    'wind_deg': 277,
    'wind_gust': 13.26,
    'weather': [{'id': 803,
      'main': 'Clouds',
      'description': 'broken clouds',
      'icon': '04d'}],
    'clouds': 74,
    'pop': 0,
    'uvi': 2},
   {'dt': 1761130800,
    'sunrise': 1761114873,
    'sunset': 1761152381,
    'moonrise': 1761119100,
    'moonset': 1761151980,
    'moon_phase': 0.03,
    'summary': 'Expect a day of partly cloudy with rain',
    'temp': {'day': 12.75,
     'min': 9.86,
     'max': 16.51,
     'night': 16.51,
     'eve': 16.25,
     'morn': 9.86},
    'feels_like': {'day': 12.4, 'night': 16.59, 'eve': 16.31, 'morn': 7.35},
    'pressure': 1006,
    'humidity': 89,
    'dew_point': 11.04,
    'wind_speed': 7.68,
    'wind_deg': 217,
    'wind_gust': 15.48,
    'weather': [{'id': 500,
      'main': 'Rain',
      'description': 'light rain',
      'icon': '10d'}],
    'clouds': 100,
    'pop': 1,
    'rain': 3.33,
    'uvi': 2}]},
 'Le Havre': {'lat': 49.4938975,
  'lon': 0.1079732,
  'daily_forecast': [{'dt': 1760526000,
    'sunrise': 1760509236,
    'sunset': 1760548183,
    'moonrise': 1760483700,
    'moonset': 1760541060,
    'moon_phase': 0.81,
    'summary': 'There will be partly cloudy today',
    'temp': {'day': 15.73,
     'min': 12.83,
     'max': 16.01,
     'night': 15.29,
     'eve': 15.51,
     'morn': 14.77},
    'feels_like': {'day': 15, 'night': 14.65, 'eve': 15, 'morn': 13.97},
    'pressure': 1027,
    'humidity': 63,
    'dew_point': 8.96,
    'wind_speed': 5.91,
    'wind_deg': 58,
    'wind_gust': 9.04,
    'weather': [{'id': 803,
      'main': 'Clouds',
      'description': 'broken clouds',
      'icon': '04d'}],
    'clouds': 76,
    'pop': 0.03,
    'uvi': 2.22},
   {'dt': 1760612400,
    'sunrise': 1760595730,
    'sunset': 1760634463,
    'moonrise': 1760574780,
    'moonset': 1760628540,
    'moon_phase': 0.84,
    'summary': 'You can expect partly cloudy in the morning, with clearing in the afternoon',
    'temp': {'day': 15.94,
     'min': 13.35,
     'max': 17.08,
     'night': 13.35,
     'eve': 15.98,
     'morn': 14.63},
    'feels_like': {'day': 15.1, 'night': 12.54, 'eve': 15.23, 'morn': 13.85},
    'pressure': 1025,
    'humidity': 58,
    'dew_point': 7.51,
    'wind_speed': 6.49,
    'wind_deg': 62,
    'wind_gust': 10.67,
    'weather': [{'id': 804,
      'main': 'Clouds',
      'description': 'overcast clouds',
      'icon': '04d'}],
    'clouds': 100,
    'pop': 0,
    'uvi': 2.36},
   {'dt': 1760698800,
    'sunrise': 1760682224,
    'sunset': 1760720744,
    'moonrise': 1760665800,
    'moonset': 1760715780,
    'moon_phase': 0.87,
    'summary': 'Expect a day of partly cloudy with clear spells',
    'temp': {'day': 16.69,
     'min': 11.39,
     'max': 17.93,
     'night': 12.94,
     'eve': 16.31,
     'morn': 11.48},
    'feels_like': {'day': 15.85, 'night': 12.04, 'eve': 15.48, 'morn': 10.67},
    'pressure': 1024,
    'humidity': 55,
    'dew_point': 7.34,
    'wind_speed': 6.5,
    'wind_deg': 76,
    'wind_gust': 10.6,
    'weather': [{'id': 801,
      'main': 'Clouds',
      'description': 'few clouds',
      'icon': '02d'}],
    'clouds': 11,
    'pop': 0,
    'uvi': 2.3},
   {'dt': 1760785200,

In [ ]:
with open("dict_backup.json", "w") as f:
    json.dump(obj=weather_dict, fp=f)

## Making a First DataFrame with Weather Data for Each Destination

In [ ]:
destination_list = ["Mont Saint Michel", "St Malo", "Bayeux", "Le Havre", "Rouen", "Paris", "Amiens", "Lille", "Strasbourg", "Chateau du Haut Koenigsbourg", "Colmar", "Eguisheim",
                    "Besancon", "Dijon", "Annecy", "Grenoble", "Lyon", "Gorges du Verdon", "Bormes les Mimosas", "Cassis", "Marseille", "Aix en Provence", "Avignon", "Uzes", "Nimes",
                    "Aigues Mortes", "Saintes Maries de la mer", "Collioure", "Carcassonne", "Ariege", "Toulouse", "Montauban", "Biarritz", "Bayonne", "La Rochelle"]

weather_df_dict = {"place_id" : ["msm", "sml", "byx", "lhv", "ron", "prs", "ams", "lll", "sbg", "chk", "clm", "egh", "bsc", "djn", "anc", "grb", "lyn", "gdv",
                                 "blm", "css", "msl", "xep", "avg", "uzs", "nms", "agm", "smm", "clr", "crc", "arg", "tls", "mtb", "brz", "byn", "lrc"],
                   "placename" : destination_list,
                   "lon" : [],
                   "lat" : [],
                   "mean_max_temp_over_next_7_days" : [],
                   "mean_cloud_cover_over_next_7_days" : [],
                   "mean_POP_over_next_7_days" : [],
                   "bad_weather_score" : []}

for destination in destination_list:
    destination_data = weather_dict[destination]
    
    weather_df_dict["lon"].append(destination_data["lon"])
    weather_df_dict["lat"].append(destination_data["lat"])

    mean_max_temp_over_next_7_days = np.mean([day_forecast["temp"]["max"]
                                              for day_forecast in destination_data["daily_forecast"]])
    weather_df_dict["mean_max_temp_over_next_7_days"].append(mean_max_temp_over_next_7_days)

    mean_cloud_cover_over_next_7_days = np.mean([day_forecast["clouds"]
                                                 for day_forecast in destination_data["daily_forecast"]])
    weather_df_dict["mean_cloud_cover_over_next_7_days"].append(mean_cloud_cover_over_next_7_days)

    mean_POP_over_next_7_days = np.mean([day_forecast["temp"]["max"]
                                         for day_forecast in destination_data["daily_forecast"]])
    weather_df_dict["mean_POP_over_next_7_days"].append(mean_POP_over_next_7_days)

    # The instructions say that I can decide what "good weather" is, so I decided purely based on personal taste that an acceptable
    # temperature range is between 0ºC and 30ºC. If the temperature goes above 30, the score starts increasing again.
    # Since there are two "bad weather" indicators that correspond to percentages and one "good weather" indicator that doesn't,
    # I decided to modify the "good weather" value so it would be out of 100 and go down as it gets better, and thus match.
    weather_df_dict["bad_weather_score"].append(np.mean([abs(100 - ((mean_max_temp_over_next_7_days / 30) * 100)),
                                                         mean_cloud_cover_over_next_7_days,
                                                         mean_POP_over_next_7_days]))



weather_df = pd.DataFrame(weather_df_dict).sort_values(by="bad_weather_score", ascending=True)\
                                          .reset_index(drop=True)
weather_df

,place_id,placename,lon,lat,mean_max_temp_over_next_7_days,mean_cloud_cover_over_next_7_days,mean_POP_over_next_7_days,bad_weather_score
0,xep,Aix en Provence,5.447474,43.529842,20.47125,13.500,20.47125,21.911250
1,msl,Marseille,5.369953,43.296174,20.13375,15.375,20.13375,22.798750
2,avg,Avignon,4.805901,43.949249,21.85250,21.750,21.85250,23.586944
3,css,Cassis,5.539632,43.214036,19.26125,17.250,19.26125,24.102361
4,blm,Bormes les Mimosas,6.341928,43.150697,18.95125,16.750,18.95125,24.176806
5,nms,Nimes,4.360069,43.837425,22.26625,27.875,22.26625,25.306806
6,uzs,Uzes,4.419672,44.012128,21.23625,26.375,21.23625,25.607917
7,smm,Saintes Maries de la mer,4.427720,43.451592,19.32125,23.000,19.32125,25.972361
8,agm,Aigues Mortes,4.191540,43.566152,20.11000,28.125,20.11000,27.067222
9,tls,Toulouse,1.444243,43.604464,21.92250,38.000,21.92250,28.949167
10,mtb,Montauban,1.354999,44.017584,21.37250,38.750,21.37250,29.626944
11,grb,Grenoble,5.735782,45.187560,19.53750,38.375,19.53750,30.929167
12,djn,Dijon,5.041470,47.321581,15.58625,32.500,15.58625,32.044028
13,bsc,Besancon,6.024362,47.238022,16.28625,36.500,16.28625,32.832917
14,crc,Carcassonne,2.349107,43.213036,21.64250,49.125,21.64250,32.875278
15,arg,Ariege,1.406554,42.945537,18.47500,43.000,18.47500,33.297222
16,clr,Collioure,3.083155,42.525050,21.27500,49.875,21.27500,33.411111
17,lyn,Lyon,4.832011,45.757814,17.87125,43.000,17.87125,33.766806
18,lrc,La Rochelle,-1.151595,46.159732,19.13625,49.875,19.13625,35.074583
19,anc,Annecy,6.128885,45.899235,16.53625,44.000,16.53625,35.138472
20,byn,Bayonne,-1.473666,43.494514,22.26625,60.250,22.26625,36.098472
21,clm,Colmar,7.357964,48.077752,16.06000,45.875,16.06000,36.133889
22,msm,Mont Saint Michel,-1.511460,48.635954,18.33250,51.875,18.33250,36.366389
23,egh,Eguisheim,7.307962,48.044797,15.68375,45.875,15.68375,36.426528
24,gdv,Gorges du Verdon,6.328562,43.749656,15.39000,45.625,15.39000,36.571667
25,brz,Biarritz,-1.559278,43.483252,21.25375,60.250,21.25375,36.885972
26,prs,Paris,2.320041,48.858890,17.35875,57.000,17.35875,38.832083
27,chk,Chateau du Haut Koenigsbourg,7.344320,48.249411,13.56750,51.000,13.56750,39.780833
28,sbg,Strasbourg,7.750713,48.584614,16.09375,57.875,16.09375,40.107639
29,sml,St Malo,-96.953823,49.314695,12.72625,50.500,12.72625,40.268472
30,ron,Rouen,1.093966,49.440459,17.12125,75.375,17.12125,45.141806
31,byx,Bayeux,-0.702474,49.276462,17.36125,81.750,17.36125,47.080139
32,lhv,Le Havre,0.107973,49.493898,17.02000,82.000,17.02000,47.428889
33,ams,Amiens,2.295695,49.894171,16.40250,83.875,16.40250,48.534167
34,lll,Lille,3.063528,50.636565,16.16250,91.750,16.16250,51.345833

In [ ]:
weather_df.to_csv("place_weather.csv")

In [90]:
weather_df = pd.read_csv("place_weather.csv")

fig = px.scatter_map(weather_df,
                     lon="POI_lon", 
                     lat="POI_lat",
                     color="bad_weather_score",
                     title="What You Can Expect From the Weather These Next 7 Days",
                     zoom=4.5,
                     height=700,
                     width=900,
                     size_max=10,
                     size=[10]*len(weather_df),
                     color_continuous_scale=px.colors.sequential.Blackbody,
                     opacity=1)
fig.write_html("7_day_weather.html")
fig.show()

## Scraping Booking.com

I initially scraped using an elegant set of URLs populated in a loop with the set of placenames, as shown below.\
I even got it to work in a rudimentary spider a few times, but that technique permanently started giving pages without results and asking me to prove I'm not a robot before I could finish the spider (even when rotating proxies and user agents, even late at night, even when waiting 24hrs, even when putting a delay with time.sleep(), etc.).\
I found a different results page with a different structure, but it never worked with spiders: I ended up scraping the website with a script that used GET requests and Scrapy Selectors, because that worked just fine and was easier to output data in a DataFrame-friendly format with.\
If I had more time, there would probably have been ways to use spiders, such as by interacting with the Javascript through scrapy-playwright or scrapy-splash, and by checking whether the scrapy project is actually doing the obfuscation things it has to.

In [76]:
for placename in weather_df.placename.to_list():
    print(requests.get(f"https://www.booking.com/searchresults.fr.html?ss={placename}"))
    sleep(3)

<Response [200]>
<Response [200]>

KeyboardInterrupt:

In [ ]:
url = "https://www.booking.com/searchresults.fr.html?ss=%27Mont%20Saint%20Michel%27"
response = Selector(text=requests.get(url).text)

for item in response.xpath("//*[contains(@class, 'cca574b93c')]").getall(): # This class matches a pair of tags that contain all the results
    if "data-results-container" in item:
        print("found it!")

found it!

In [1]:
!python booking_spider.py

2025-10-16 00:38:12 [scrapy.utils.log] INFO: Scrapy 2.12.0 started (bot: scrapybot)
2025-10-16 00:38:12 [scrapy.utils.log] INFO: Versions: lxml 5.3.0.0, libxml2 2.13.8, cssselect 1.2.0, parsel 1.8.1, w3lib 2.1.2, Twisted 24.11.0, Python 3.13.5 | packaged by Anaconda, Inc. | (main, Jun 12 2025, 11:09:21) [Clang 14.0.6 ], pyOpenSSL 25.1.0 (OpenSSL 3.5.4 30 Sep 2025), cryptography 45.0.5, Platform macOS-10.16-x86_64-i386-64bit-Mach-O
2025-10-16 00:38:12 [scrapy.addons] INFO: Enabled addons:
[]
2025-10-16 00:38:12 [scrapy.extensions.telnet] INFO: Telnet Password: 832683c52d26ed6b
2025-10-16 00:38:13 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2025-10-16 00:38:13 [scrapy.crawler] INFO: Overridden settings:
{'LOG_LEVEL': 20, 'USER_AGENT': 'Chrome/97.0'}
2025-10-16 00:38:13 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2025-10-16 00:38:13 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2025-10-16 00:38:13 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2025-10-16 00:38:13 [scrapy.core.engine] INFO: Spider opened
2025-10-16 00:38:13 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2025-10-16 00:38:13 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
[]
2025-10-16 00:38:13 [scrapy.core.engine] INFO: Closing spider (finished)
2025-10-16 00:38:13 [scrapy.extensions.feedexport] INFO: Stored json feed (1 items) in: src/booking_locations.json
2025-10-16 00:38:13 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 253,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 6115,
 'downloader/response_count': 1,
 'downloader/response_status_count/202': 1,
 'elapsed_time_seconds': 0.325819,
 'feedexport/success_count/FileFeedStorage': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2025, 10, 15, 22, 38, 13, 464250, tzinfo=datetime.timezone.utc),
 'item_scraped_count': 1,
 'items_per_minute': None,
 'log_count/INFO': 11,
 'memusage/max': 103383040,
 'memusage/startup': 103383040,
 'response_received_count': 1,
 'responses_per_minute': None,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2025, 10, 15, 22, 38, 13, 138431, tzinfo=datetime.timezone.utc)}
2025-10-16 00:38:13 [scrapy.core.engine] INFO: Spider closed (finished)

In [15]:
with open("./src/booking_locations.json", "r") as f:
    results_dict = json.load(f)

In [ ]:
html_str = results_dict[0]["dummy_response"]
response = Selector(text=html_str)
responses = response.xpath("//*[contains(@class, 'c3bdfd4ac2 a0ab5da06c d46ff48a92 f728e61e72 d0acd69e66 c256f1a28a bc2204a477')]/div[1]/div[2]/div[1]/div[1]/div[1]/div/div[3]/text()")
for r in responses:
    print(r.get())

Installé dans des espaces verts à seulement 2 km de l'abbaye du Mont-Saint-Michel, le Mercure Mont Saint Michel propose des chambres spacieuses avec salle de bains privative, un bar-restaurant et de...
Situé au Mont-Saint-Michel, l’établissement 2 étoiles Le Duguesclin possède un restaurant et un bar.
La Vieille Auberge vous accueille dans le village médiéval du Mont-Saint-Michel, à quelques pas de la célèbre abbaye.
Séjournez dans un hôtel historique au cœur du Mont Saint-Michel. L'Hôtel La Mère Poulard, situé au cœur du Mont Saint-Michel, a conservé le charme authentique des auberges traditionnelles d'autrefois....
L’Hotel Vert vous propose des chambres décorées dans des tons pastel, dotées d’une salle de bains privative, d’une télévision ainsi que d’une connexion Wi-Fi gratuite.
Occupant 2 bâtiments différents au cœur du Mont-Saint-Michel, l’établissement historique Les Terrasses Poulard propose des hébergements avec une vue sur la baie, le village et la rue.
Le Relais Du Roy est un hôtel 3 étoiles situé au bord du Couesnon, à seulement 1,5 km du Mont Saint-Michel et à 50 mètres de la navette gratuite.
Situé au pied de l’abbaye, l’hôtel Le Mouton Blanc vous accueille dans son bâtiment historique datant du XIVe siècle. Il propose des chambres confortables à la décoration simple et chaleureuse.
Niché dans un écrin de verdure, à seulement 2 km du Mont-Saint-Michel, Le Saint Aubert vous accueille dans un cadre chaleureux et convivial.
Située sur le Mont-Saint-Michel, l'Auberge Saint Pierre est composée de petits bâtiments à colombages datant du XIVe siècle.
Le Relais Saint Michel vous accueille face à la baie du Mont-Saint-Michel.
Hotel Gabriel is located 1.6 Km from Mont Saint-Michel. It offers free Wi-Fi access and en suite rooms just a 25-minute walk from the walls of the old city.
L’hébergement Chez Adèle se trouve au Mont-Saint-Michel, à respectivement quelques pas, 200 mètres et 29 km de ces lieux d’intérêt : Abbaye du Mont Saint Michel, Mont Saint-Michel et Scriptorial...
L’hébergement Appart Standing - La Coque d'Or vous accueille au Mont-Saint-Michel, à respectivement 200 mètres, quelques pas et 29 km de ces lieux d’intérêt : Abbaye du Mont Saint Michel, Mont...
Situé au cœur du village médiéval du Mont-Saint-Michel, l'Hôtel La Croix Blanche se fera un plaisir de vous accueillir.
Offrant une vue sur le jardin, l’établissement Chambres d'hôtes La Rive - Le Mont Saint Michel possède une connexion Wi-Fi gratuite et un parking privé gratuit.
L’hébergement Maison au pied du Mont Saint Michel vous accueille à Pontorson, à respectivement 8,7 km et 21 km de ces lieux d’intérêt : Mont Saint-Michel et Scriptorial d'Avranches.
Situé dans la campagne normande, cet hôtel dispose d’une connexion Wi-Fi gratuite.
Offrant une vue sur le jardin, l’établissement Mon Saint Michel possède une connexion Wi-Fi gratuite et un parking privé gratuit.
Situé à Courtils, l’établissement Le Marquis De La Guintre propose une connexion Wi-Fi gratuite, une terrasse, un restaurant et un bar. Un petit-déjeuner continental est servi sur place.
L’établissement Etoile des Grèves vous accueille à 8,2 km de ce lieu d’intérêt : Abbaye du Mont Saint Michel. Il comprend une connexion Wi-Fi gratuite et un parking privé gratuit.
Situé à Pontorson, l’hébergement Gîte au pied du Mont Saint Michel offre une vue sur le jardin. Il possède une terrasse et une connexion Wi-Fi gratuite.
Situé à Huisnes-sur-Mer, l’établissement A l ombre du Mont Saint Michel possède une connexion Wi-Fi gratuite, un jardin, un salon commun et une terrasse.
Proposant un salon commun et offrant une vue sur le jardin, l’hébergement Gîte de la Grève se trouve à Beauvoir, à respectivement 5,1 km et 5,1 km de ces lieux d’intérêt : Abbaye du Mont Saint Michel...
L’Apparthôtel Mont Saint Michel - Résidence Fleurdumont propose un hébergement acceptant les animaux domestiques à Beauvoir, à 4,4 km de l’abbaye du Mont-Saint-Michel.

#### Trying to Access the Button to Load More Results

It turns out that it only appears if the user scrolls down, but scrapy alone doesn't allow one to interact with the website other than reading a frozen version of the HTML.

In [ ]:
url = "https://www.booking.com/searchresults.fr.html?ss=%27Mont%20Saint%20Michel%27"

response = requests.get(url).text

("Afficher plus de résultats" in response)

False

In [55]:
response.find("Afficher plus de résultats")

550829

In [57]:
response[550800:550900]

'"sr_mdot_load_more_results":"Afficher plus de résultats","sr_nodates_show_prices":"Voir les tarifs",'

#### Researching How to Access the Coordinates of Each Hotel, Which Requires Loading Each Hotel Page

In [7]:
url = "https://www.booking.com/hotel/fr/le-marquis-de-la-guintre.fr.html?aid=304142&label=gen173nr-10CAQoggJCHXNlYXJjaF8nbGUgbW9udCBzYWludCBtaWNoZWwnSA1YBGhNiAEBmAEzuAEKyAEF2AED6AEB-AEBiAIBqAIBuAK-xsDHBsACAdICJDA4MjZmMTY5LTgzZjItNDBiMy1iYTkwLTI0ZTU5NDIwOTUwNtgCAeACAQ&ucfs=1&arphpl=1&group_adults=2&req_adults=2&no_rooms=1&group_children=0&req_children=0&hpos=20&hapos=20&sr_order=popularity&srpvid=1f089f9f97140053&srepoch=1760568128&from=searchresults"
coords_response = Selector(text=requests.get(url).text)

In [8]:
coords_responses = coords_response.xpath("//*[contains(@id, 'map_trigger_header')]").attrib["data-atlas-latlng"]
print(coords_responses.split(","))

['48.6248647057706', '-1.44534185528755']

In [ ]:
# This is a separate spider file that I was planning on calling from within the main spider,
# in order to scrape the coordinates and return them to the main spider
import hotel_coordinates_spider

result = hotel_coordinates_spider.get("https://www.booking.com/hotel/fr/le-marquis-de-la-guintre.fr.html?aid=304142&label=gen173nr-10CAQoggJCHXNlYXJjaF8nbGUgbW9udCBzYWludCBtaWNoZWwnSA1YBGhNiAEBmAEzuAEKyAEF2AED6AEB-AEBiAIBqAIBuAK-xsDHBsACAdICJDA4MjZmMTY5LTgzZjItNDBiMy1iYTkwLTI0ZTU5NDIwOTUwNtgCAeACAQ&ucfs=1&arphpl=1&group_adults=2&req_adults=2&no_rooms=1&group_children=0&req_children=0&hpos=20&hapos=20&sr_order=popularity&srpvid=1f089f9f97140053&srepoch=1760568128&from=searchresults")

In [2]:
("map_trigger_header" in result)

False

#### Since No Spider is Working, Even When Rotating Proxies and User Agents, but GET Requests Paired With Scrapy Selectors Work Fine, I'll Scrape Using the Latter and Try Again Later

In [ ]:
url = "https://www.booking.com/searchresults.fr.html?ss=Bayeux&ssne=Bayeux&ssne_untouched=Bayeux&highlighted_hotels=9807677&label=gen000nr-10CAsoTUINbGUtcGV0aXQtbWFsb0gNWARoTYgBAZgBM7gBBcgBHtgBA-gBAfgBAYgCAagCAbgC3Z_IxwbAAgHSAiQzNWNhYmJmNy05MmU2LTQ2NTQtOGViZi0wNDk0OWYwYjRjMTbYAgHgAgE&aid=304142&lang=fr&sb=1&src_elem=sb&src=hotel&dest_id=-1410836&dest_type=city&group_adults=2&no_rooms=1&group_children=0"
coords_response = Selector(text=requests.get(url).text)

coords_responses = coords_response.xpath("//*[contains(@class, 'b071d3eccd afd3558156 ecc7830bbb')]/div[1]/div[1]/div[1]/div[1]/a/div[1]/h3/div[1]/text()").getall()
print(coords_responses)

['Domaine de Bayeux', 'Villa Lara Hotel', 'Hôtel De Brunville & Spa', "Hotel Le Lion D'Or et Restaurant La Table Du Lion", 'Hotel Reine Mathilde', "Hôtel d'Argouges", 'Belle Normandy', 'Le Declic', 'La Maison de Mathilde', 'Hôtel Le Saint Patrice']

In [53]:
len(coords_responses)

10

#### What Did the Job

In [ ]:
# Programmatically getting or making search page URLs didn't work, so I resorted to manually getting them.
# If I had hundreds or thousands of those to get, I would have used Selenium, scrapy-playwright or scrapy-splash
# to programmatically write the place names in the search field, press the search button, and scrape what came up.

# I of course tried simply changing the placenames, like I was initially doing, but that doesn't give hotel results.

urls_dict = {
    "Mont Saint Michel" : "https://www.booking.com/searchresults.fr.html?ss=Le+Mont-Saint-Michel%2C+Basse-Normandie%2C+France&efdco=1&label=gen173nr-10CAEoggI46AdIM1gEaE2IAQGYATO4AQfIAQ_YAQPoAQH4AQGIAgGoAgG4AozwyMcGwAIB0gIkN2ZlNDhmMDQtNTg3Mi00NzI3LWExNWEtZjI4YjNiNDc4YTRh2AIB4AIB&sid=ec92b03eccf337e979d9b3cac5b2d333&aid=304142&lang=fr&sb=1&src_elem=sb&src=index&dest_id=900039327&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=fr&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=7ed95886238f0057&ac_meta=GhA3ZWQ5NTg4NjIzOGYwMDU3IAAoATICZnI6B2xlIG1vbnRAAEoAUAA%3D&group_adults=2&no_rooms=1&group_children=0",
    "St Malo" : "https://www.booking.com/searchresults.fr.html?ss=Saint-Malo%2C+Bretagne%2C+France&efdco=1&label=gen173nr-10CAEoggI46AdIM1gEaE2IAQGYATO4AQfIAQ_YAQPoAQH4AQGIAgGoAgG4AozwyMcGwAIB0gIkN2ZlNDhmMDQtNTg3Mi00NzI3LWExNWEtZjI4YjNiNDc4YTRh2AIB4AIB&sid=ec92b03eccf337e979d9b3cac5b2d333&aid=304142&lang=fr&sb=1&src_elem=sb&src=searchresults&dest_id=-1466824&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=fr&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=b3c958dde02a00f2&ac_meta=GhBiM2M5NThkZGUwMmEwMGYyIAAoATICZnI6BXNhaW50QABKAFAA&group_adults=2&no_rooms=1&group_children=0",
    "Bayeux" : "https://www.booking.com/searchresults.fr.html?ss=Bayeux%2C+Basse-Normandie%2C+France&efdco=1&label=gen173nr-10CAEoggI46AdIM1gEaE2IAQGYATO4AQfIAQ_YAQPoAQH4AQGIAgGoAgG4AozwyMcGwAIB0gIkN2ZlNDhmMDQtNTg3Mi00NzI3LWExNWEtZjI4YjNiNDc4YTRh2AIB4AIB&sid=ec92b03eccf337e979d9b3cac5b2d333&aid=304142&lang=fr&sb=1&src_elem=sb&src=searchresults&dest_id=-1410836&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=fr&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=67c458f868cc0234&ac_meta=GhA2N2M0NThmODY4Y2MwMjM0IAAoATICZnI6BmJheWV1eEAASgBQAA%3D%3D&group_adults=2&no_rooms=1&group_children=0",
    "Le Havre" : "https://www.booking.com/searchresults.fr.html?ss=Le+Havre%2C+Haute-Normandie%2C+France&efdco=1&label=gen173nr-10CAEoggI46AdIM1gEaE2IAQGYATO4AQfIAQ_YAQPoAQH4AQGIAgGoAgG4AozwyMcGwAIB0gIkN2ZlNDhmMDQtNTg3Mi00NzI3LWExNWEtZjI4YjNiNDc4YTRh2AIB4AIB&sid=ec92b03eccf337e979d9b3cac5b2d333&aid=304142&lang=fr&sb=1&src_elem=sb&src=searchresults&dest_id=-1441598&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=fr&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=551f59c5b0ce1b9c&ac_meta=GhA1NTFmNTljNWIwY2UxYjljIAAoATICZnI6CExlIGhhdnJlQABKAFAA&group_adults=2&no_rooms=1&group_children=0",
    "Rouen" : "https://www.booking.com/searchresults.fr.html?ss=Rouen%2C+Haute-Normandie%2C+France&efdco=1&label=gen173nr-10CAEoggI46AdIM1gEaE2IAQGYATO4AQfIAQ_YAQPoAQH4AQGIAgGoAgG4AozwyMcGwAIB0gIkN2ZlNDhmMDQtNTg3Mi00NzI3LWExNWEtZjI4YjNiNDc4YTRh2AIB4AIB&sid=ec92b03eccf337e979d9b3cac5b2d333&aid=304142&lang=fr&sb=1&src_elem=sb&src=searchresults&dest_id=-1462807&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=fr&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=ce3f59f3d9230239&ac_meta=GhBjZTNmNTlmM2Q5MjMwMjM5IAAoATICZnI6BXJvdWVuQABKAFAA&group_adults=2&no_rooms=1&group_children=0",
    "Paris" : "https://www.booking.com/searchresults.fr.html?ss=Paris&efdco=1&label=gen173nr-10CAEoggI46AdIM1gEaE2IAQGYATO4AQfIAQ_YAQPoAQH4AQGIAgGoAgG4AozwyMcGwAIB0gIkN2ZlNDhmMDQtNTg3Mi00NzI3LWExNWEtZjI4YjNiNDc4YTRh2AIB4AIB&sid=ec92b03eccf337e979d9b3cac5b2d333&aid=304142&lang=fr&sb=1&src_elem=sb&src=searchresults&dest_id=-1456928&dest_type=city&group_adults=2&no_rooms=1&group_children=0",
    "Amiens" : "https://www.booking.com/searchresults.fr.html?ss=Amiens%2C+Picardie%2C+France&efdco=1&label=gen173nr-10CAEoggI46AdIM1gEaE2IAQGYATO4AQfIAQ_YAQPoAQH4AQGIAgGoAgG4AozwyMcGwAIB0gIkN2ZlNDhmMDQtNTg3Mi00NzI3LWExNWEtZjI4YjNiNDc4YTRh2AIB4AIB&sid=ec92b03eccf337e979d9b3cac5b2d333&aid=304142&lang=fr&sb=1&src_elem=sb&src=searchresults&dest_id=-1407447&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=fr&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=8df858d3a0f304c6&ac_meta=GhA4ZGY4NThkM2EwZjMwNGM2IAAoATICZnI6BmFtaWVuc0AASgBQAA%3D%3D&group_adults=2&no_rooms=1&group_children=0",
    "Lille" : "https://www.booking.com/searchresults.fr.html?ss=Lille%2C+Nord-Pas-de-Calais%2C+France&efdco=1&label=gen173nr-10CAEoggI46AdIM1gEaE2IAQGYATO4AQfIAQ_YAQPoAQH4AQGIAgGoAgG4AozwyMcGwAIB0gIkN2ZlNDhmMDQtNTg3Mi00NzI3LWExNWEtZjI4YjNiNDc4YTRh2AIB4AIB&sid=ec92b03eccf337e979d9b3cac5b2d333&aid=304142&lang=fr&sb=1&src_elem=sb&src=searchresults&dest_id=-1447079&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=fr&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=c84b5b8161dd010a&ac_meta=GhBjODRiNWI4MTYxZGQwMTBhIAAoATICZnI6BUxpbGxlQABKAFAA&group_adults=2&no_rooms=1&group_children=0",
    "Strasbourg" : "https://www.booking.com/searchresults.fr.html?ss=Strasbourg%2C+Alsace%2C+France&efdco=1&label=gen173nr-10CAEoggI46AdIM1gEaE2IAQGYATO4AQfIAQ_YAQPoAQH4AQGIAgGoAgG4AozwyMcGwAIB0gIkN2ZlNDhmMDQtNTg3Mi00NzI3LWExNWEtZjI4YjNiNDc4YTRh2AIB4AIB&sid=ec92b03eccf337e979d9b3cac5b2d333&aid=304142&lang=fr&sb=1&src_elem=sb&src=searchresults&dest_id=-1471697&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=fr&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=17e25b86c68f0268&ac_meta=GhAxN2UyNWI4NmM2OGYwMjY4IAAoATICZnI6ClN0cmFzYm91cmdAAEoAUAA%3D&group_adults=2&no_rooms=1&group_children=0",
    "Chateau du Haut Koenigsbourg" : "https://www.booking.com/searchresults.fr.html?ss=Ch%C3%A2teau+du+Haut-K%C5%93nigsbourg%2C+Saint-Hippolyte%2C+Alsace%2C+France&efdco=1&label=gen173nr-10CAEoggI46AdIM1gEaE2IAQGYATO4AQfIAQ_YAQPoAQH4AQGIAgGoAgG4AozwyMcGwAIB0gIkN2ZlNDhmMDQtNTg3Mi00NzI3LWExNWEtZjI4YjNiNDc4YTRh2AIB4AIB&sid=ec92b03eccf337e979d9b3cac5b2d333&aid=304142&lang=fr&sb=1&src_elem=sb&src=searchresults&dest_id=204055&dest_type=landmark&ac_position=0&ac_click_type=b&ac_langcode=fr&ac_suggestion_list_length=4&search_selected=true&search_pageview_id=c8265bac979f04ca&ac_meta=GhBjODI2NWJhYzk3OWYwNGNhIAAoATICZnI6HENoYXRlYXUgZHUgSGF1dCBLb2VuaWdzYm91cmdAAEoAUAA%3D&group_adults=2&no_rooms=1&group_children=0",
    "Colmar" : "https://www.booking.com/searchresults.fr.html?ss=Colmar%2C+Alsace%2C+France&efdco=1&label=gen173nr-10CAEoggI46AdIM1gEaE2IAQGYATO4AQfIAQ_YAQPoAQH4AQGIAgGoAgG4AozwyMcGwAIB0gIkN2ZlNDhmMDQtNTg3Mi00NzI3LWExNWEtZjI4YjNiNDc4YTRh2AIB4AIB&sid=ec92b03eccf337e979d9b3cac5b2d333&aid=304142&lang=fr&sb=1&src_elem=sb&src=searchresults&dest_id=-1421049&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=fr&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=e9e05bcb952204e0&ac_meta=GhBlOWUwNWJjYjk1MjIwNGUwIAAoATICZnI6BkNvbG1hckAASgBQAA%3D%3D&group_adults=2&no_rooms=1&group_children=0",
    "Eguisheim" : "https://www.booking.com/searchresults.fr.html?ss=Eguisheim%2C+Alsace%2C+France&efdco=1&label=gen173nr-10CAEoggI46AdIM1gEaE2IAQGYATO4AQfIAQ_YAQPoAQH4AQGIAgGoAgG4AozwyMcGwAIB0gIkN2ZlNDhmMDQtNTg3Mi00NzI3LWExNWEtZjI4YjNiNDc4YTRh2AIB4AIB&sid=ec92b03eccf337e979d9b3cac5b2d333&aid=304142&lang=fr&sb=1&src_elem=sb&src=searchresults&dest_id=-1425030&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=fr&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=5f365bf98ca301c7&ac_meta=GhA1ZjM2NWJmOThjYTMwMWM3IAAoATICZnI6B2VndWlzaGVAAEoAUAA%3D&group_adults=2&no_rooms=1&group_children=0",
    "Besancon" : "https://www.booking.com/searchresults.fr.html?ss=Besan%C3%A7on%2C+Franche-Comt%C3%A9%2C+France&efdco=1&label=gen173nr-10CAEoggI46AdIM1gEaE2IAQGYATO4AQfIAQ_YAQPoAQH4AQGIAgGoAgG4AozwyMcGwAIB0gIkN2ZlNDhmMDQtNTg3Mi00NzI3LWExNWEtZjI4YjNiNDc4YTRh2AIB4AIB&sid=ec92b03eccf337e979d9b3cac5b2d333&aid=304142&lang=fr&sb=1&src_elem=sb&src=searchresults&dest_id=-1412198&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=fr&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=accc5c2e1a2a0181&ac_meta=GhBhY2NjNWMyZTFhMmEwMTgxIAAoATICZnI6BUJlc2FuQABKAFAA&group_adults=2&no_rooms=1&group_children=0",
    "Dijon" : "https://www.booking.com/searchresults.fr.html?ss=Dijon%2C+Bourgogne%2C+France&efdco=1&label=gen173nr-10CAEoggI46AdIM1gEaE2IAQGYATO4AQfIAQ_YAQPoAQH4AQGIAgGoAgG4AozwyMcGwAIB0gIkN2ZlNDhmMDQtNTg3Mi00NzI3LWExNWEtZjI4YjNiNDc4YTRh2AIB4AIB&sid=ec92b03eccf337e979d9b3cac5b2d333&aid=304142&lang=fr&sb=1&src_elem=sb&src=searchresults&dest_id=-1423981&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=fr&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=3a595c6d9f1a0373&ac_meta=GhAzYTU5NWM2ZDlmMWEwMzczIAAoATICZnI6BURpam9uQABKAFAA&group_adults=2&no_rooms=1&group_children=0",
    "Annecy" : "https://www.booking.com/searchresults.fr.html?ss=Annecy%2C+Rh%C3%B4ne-Alpes%2C+France&efdco=1&label=gen173nr-10CAEoggI46AdIM1gEaE2IAQGYATO4AQfIAQ_YAQPoAQH4AQGIAgGoAgG4AozwyMcGwAIB0gIkN2ZlNDhmMDQtNTg3Mi00NzI3LWExNWEtZjI4YjNiNDc4YTRh2AIB4AIB&sid=ec92b03eccf337e979d9b3cac5b2d333&aid=304142&lang=fr&sb=1&src_elem=sb&src=searchresults&dest_id=-1407760&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=fr&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=ed215c8a91ec0412&ac_meta=GhBlZDIxNWM4YTkxZWMwNDEyIAAoATICZnI6BkFubmVjeUAASgBQAA%3D%3D&group_adults=2&no_rooms=1&group_children=0",
    "Grenoble" : "https://www.booking.com/searchresults.fr.html?ss=Grenoble%2C+Rh%C3%B4ne-Alpes%2C+France&efdco=1&label=gen173nr-10CAEoggI46AdIM1gEaE2IAQGYATO4AQfIAQ_YAQPoAQH4AQGIAgGoAgG4AozwyMcGwAIB0gIkN2ZlNDhmMDQtNTg3Mi00NzI3LWExNWEtZjI4YjNiNDc4YTRh2AIB4AIB&sid=ec92b03eccf337e979d9b3cac5b2d333&aid=304142&lang=fr&sb=1&src_elem=sb&src=searchresults&dest_id=-1430647&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=fr&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=a6f15c909e380171&ac_meta=GhBhNmYxNWM5MDllMzgwMTcxIAAoATICZnI6CEdyZW5vYmxlQABKAFAA&group_adults=2&no_rooms=1&group_children=0",
    "Lyon" : "https://www.booking.com/searchresults.fr.html?ss=Lyon%2C+Rh%C3%B4ne-Alpes%2C+France&efdco=1&label=gen173nr-10CAEoggI46AdIM1gEaE2IAQGYATO4AQfIAQ_YAQPoAQH4AQGIAgGoAgG4AozwyMcGwAIB0gIkN2ZlNDhmMDQtNTg3Mi00NzI3LWExNWEtZjI4YjNiNDc4YTRh2AIB4AIB&sid=ec92b03eccf337e979d9b3cac5b2d333&aid=304142&lang=fr&sb=1&src_elem=sb&src=searchresults&dest_id=-1448468&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=fr&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=9fc25ce0325519a5&ac_meta=GhA5ZmMyNWNlMDMyNTUxOWE1IAAoATICZnI6BEx5b25AAEoAUAA%3D&group_adults=2&no_rooms=1&group_children=0",
    "Gorges du Verdon" : "https://www.booking.com/searchresults.fr.html?ss=Gorges+du+Verdon%2C+France&efdco=1&label=gen173nr-10CAEoggI46AdIM1gEaE2IAQGYATO4AQfIAQ_YAQPoAQH4AQGIAgGoAgG4AozwyMcGwAIB0gIkN2ZlNDhmMDQtNTg3Mi00NzI3LWExNWEtZjI4YjNiNDc4YTRh2AIB4AIB&sid=ec92b03eccf337e979d9b3cac5b2d333&aid=304142&lang=fr&sb=1&src_elem=sb&src=searchresults&dest_id=2746&dest_type=region&ac_position=0&ac_click_type=b&ac_langcode=fr&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=ca845d59d3e0082a&ac_meta=GhBjYTg0NWQ1OWQzZTAwODJhIAAoATICZnI6CmdvcmdlcyBkdSBAAEoAUAA%3D&group_adults=2&no_rooms=1&group_children=0",
    "Bormes les Mimosas" : "https://www.booking.com/searchresults.fr.html?ss=Bormes-les-Mimosas%2C+Provence-Alpes-C%C3%B4te+d%27Azur%2C+France&efdco=1&label=gen173nr-10CAEoggI46AdIM1gEaE2IAQGYATO4AQfIAQ_YAQPoAQH4AQGIAgGoAgG4AozwyMcGwAIB0gIkN2ZlNDhmMDQtNTg3Mi00NzI3LWExNWEtZjI4YjNiNDc4YTRh2AIB4AIB&sid=ec92b03eccf337e979d9b3cac5b2d333&aid=304142&lang=fr&sb=1&src_elem=sb&src=searchresults&dest_id=-1413801&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=fr&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=d2b95d8c681004ba&ac_meta=GhBkMmI5NWQ4YzY4MTAwNGJhIAAoATICZnI6DmJvcm1lcyBsZXMgbWltQABKAFAA&group_adults=2&no_rooms=1&group_children=0",
    "Cassis" : "https://www.booking.com/searchresults.fr.html?ss=Cassis%2C+Provence-Alpes-C%C3%B4te+d%27Azur%2C+France&efdco=1&label=gen173nr-10CAEoggI46AdIM1gEaE2IAQGYATO4AQfIAQ_YAQPoAQH4AQGIAgGoAgG4AozwyMcGwAIB0gIkN2ZlNDhmMDQtNTg3Mi00NzI3LWExNWEtZjI4YjNiNDc4YTRh2AIB4AIB&sid=ec92b03eccf337e979d9b3cac5b2d333&aid=304142&lang=fr&sb=1&src_elem=sb&src=searchresults&dest_id=-1416912&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=fr&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=d4b25e043f2e0578&ac_meta=GhBkNGIyNWUwNDNmMmUwNTc4IAAoATICZnI6BkNhc3Npc0AASgBQAA%3D%3D&group_adults=2&no_rooms=1&group_children=0",
    "Marseille" : "https://www.booking.com/searchresults.fr.html?ss=Marseille%2C+Provence-Alpes-C%C3%B4te+d%27Azur%2C+France&efdco=1&label=gen173nr-10CAEoggI46AdIM1gEaE2IAQGYATO4AQfIAQ_YAQPoAQH4AQGIAgGoAgG4AozwyMcGwAIB0gIkN2ZlNDhmMDQtNTg3Mi00NzI3LWExNWEtZjI4YjNiNDc4YTRh2AIB4AIB&sid=ec92b03eccf337e979d9b3cac5b2d333&aid=304142&lang=fr&sb=1&src_elem=sb&src=searchresults&dest_id=-1449947&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=fr&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=4f705e1f2592000e&ac_meta=GhA0ZjcwNWUxZjI1OTIwMDBlIAAoATICZnI6CW1hcnNlaWxsZUAASgBQAA%3D%3D&group_adults=2&no_rooms=1&group_children=0",
    "Aix en Provence" : "https://www.booking.com/searchresults.fr.html?ss=Aix-en-Provence%2C+Provence-Alpes-C%C3%B4te+d%27Azur%2C+France&efdco=1&label=gen173nr-10CAEoggI46AdIM1gEaE2IAQGYATO4AQfIAQ_YAQPoAQH4AQGIAgGoAgG4AozwyMcGwAIB0gIkN2ZlNDhmMDQtNTg3Mi00NzI3LWExNWEtZjI4YjNiNDc4YTRh2AIB4AIB&sid=ec92b03eccf337e979d9b3cac5b2d333&aid=304142&lang=fr&sb=1&src_elem=sb&src=searchresults&dest_id=-1406939&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=fr&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=2c455e36447f0190&ac_meta=GhAyYzQ1NWUzNjQ0N2YwMTkwIAAoATICZnI6BmFpeCBlbkAASgBQAA%3D%3D&group_adults=2&no_rooms=1&group_children=0",
    "Avignon" : "https://www.booking.com/searchresults.fr.html?ss=Avignon%2C+Provence-Alpes-C%C3%B4te+d%27Azur%2C+France&efdco=1&label=gen173nr-10CAEoggI46AdIM1gEaE2IAQGYATO4AQfIAQ_YAQPoAQH4AQGIAgGoAgG4AozwyMcGwAIB0gIkN2ZlNDhmMDQtNTg3Mi00NzI3LWExNWEtZjI4YjNiNDc4YTRh2AIB4AIB&sid=ec92b03eccf337e979d9b3cac5b2d333&aid=304142&lang=fr&sb=1&src_elem=sb&src=searchresults&dest_id=-1409631&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=fr&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=ab305e5809190326&ac_meta=GhBhYjMwNWU1ODA5MTkwMzI2IAAoATICZnI6B0F2aWdub25AAEoAUAA%3D&group_adults=2&no_rooms=1&group_children=0",
    "Uzes" : "https://www.booking.com/searchresults.fr.html?ss=Uz%C3%A8s%2C+Languedoc-Roussillon%2C+France&efdco=1&label=gen173nr-10CAEoggI46AdIM1gEaE2IAQGYATO4AQfIAQ_YAQPoAQH4AQGIAgGoAgG4AozwyMcGwAIB0gIkN2ZlNDhmMDQtNTg3Mi00NzI3LWExNWEtZjI4YjNiNDc4YTRh2AIB4AIB&sid=ec92b03eccf337e979d9b3cac5b2d333&aid=304142&lang=fr&sb=1&src_elem=sb&src=searchresults&dest_id=-1474231&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=fr&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=427b5e5cd0cb0443&ac_meta=GhA0MjdiNWU1Y2QwY2IwNDQzIAAoATICZnI6BHV6ZXNAAEoAUAA%3D&group_adults=2&no_rooms=1&group_children=0",
    "Nimes" : "https://www.booking.com/searchresults.fr.html?ss=N%C3%AEmes%2C+Languedoc-Roussillon%2C+France&efdco=1&label=gen173nr-10CAEoggI46AdIM1gEaE2IAQGYATO4AQfIAQ_YAQPoAQH4AQGIAgGoAgG4AozwyMcGwAIB0gIkN2ZlNDhmMDQtNTg3Mi00NzI3LWExNWEtZjI4YjNiNDc4YTRh2AIB4AIB&sid=ec92b03eccf337e979d9b3cac5b2d333&aid=304142&lang=fr&sb=1&src_elem=sb&src=searchresults&dest_id=-1455068&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=fr&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=ab305e6c190d023a&ac_meta=GhBhYjMwNWU2YzE5MGQwMjNhIAAoATICZnI6BW5pbWVzQABKAFAA&group_adults=2&no_rooms=1&group_children=0",
    "Aigues Mortes" : "https://www.booking.com/searchresults.fr.html?ss=Aigues-Mortes%2C+Languedoc-Roussillon%2C+France&efdco=1&label=gen173nr-10CAEoggI46AdIM1gEaE2IAQGYATO4AQfIAQ_YAQPoAQH4AQGIAgGoAgG4AozwyMcGwAIB0gIkN2ZlNDhmMDQtNTg3Mi00NzI3LWExNWEtZjI4YjNiNDc4YTRh2AIB4AIB&sid=ec92b03eccf337e979d9b3cac5b2d333&aid=304142&lang=fr&sb=1&src_elem=sb&src=searchresults&dest_id=-1406800&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=fr&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=7c9c5e84e36d0537&ac_meta=GhA3YzljNWU4NGUzNmQwNTM3IAAoATICZnI6BmFpZ3Vlc0AASgBQAA%3D%3D&group_adults=2&no_rooms=1&group_children=0",
    "Saintes Maries de la mer" : "https://www.booking.com/searchresults.fr.html?ss=Les+Saintes-Maries-de-la-Mer%2C+Provence-Alpes-C%C3%B4te+d%27Azur%2C+France&efdco=1&label=gen173nr-10CAEoggI46AdIM1gEaE2IAQGYATO4AQfIAQ_YAQPoAQH4AQGIAgGoAgG4AozwyMcGwAIB0gIkN2ZlNDhmMDQtNTg3Mi00NzI3LWExNWEtZjI4YjNiNDc4YTRh2AIB4AIB&sid=ec92b03eccf337e979d9b3cac5b2d333&aid=304142&lang=fr&sb=1&src_elem=sb&src=searchresults&dest_id=-1465138&dest_type=city&ac_position=1&ac_click_type=b&ac_langcode=fr&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=190c5e9734b11046&ac_meta=GhAxOTBjNWU5NzM0YjExMDQ2IAEoATICZnI6B3NhaW50ZXNAAEoAUAA%3D&group_adults=2&no_rooms=1&group_children=0",
    "Collioure" : "https://www.booking.com/searchresults.fr.html?ss=Collioure%2C+Languedoc-Roussillon%2C+France&efdco=1&label=gen173nr-10CAEoggI46AdIM1gEaE2IAQGYATO4AQfIAQ_YAQPoAQH4AQGIAgGoAgG4AozwyMcGwAIB0gIkN2ZlNDhmMDQtNTg3Mi00NzI3LWExNWEtZjI4YjNiNDc4YTRh2AIB4AIB&sid=ec92b03eccf337e979d9b3cac5b2d333&aid=304142&lang=fr&sb=1&src_elem=sb&src=searchresults&dest_id=-1421032&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=fr&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=c8265ea8a19a000b&ac_meta=GhBjODI2NWVhOGExOWEwMDBiIAAoATICZnI6CUNvbGxpb3VyZUAASgBQAA%3D%3D&group_adults=2&no_rooms=1&group_children=0",
    "Carcassonne" : "https://www.booking.com/searchresults.fr.html?ss=Carcassonne%2C+Languedoc-Roussillon%2C+France&efdco=1&label=gen173nr-10CAEoggI46AdIM1gEaE2IAQGYATO4AQfIAQ_YAQPoAQH4AQGIAgGoAgG4AozwyMcGwAIB0gIkN2ZlNDhmMDQtNTg3Mi00NzI3LWExNWEtZjI4YjNiNDc4YTRh2AIB4AIB&sid=ec92b03eccf337e979d9b3cac5b2d333&aid=304142&lang=fr&sb=1&src_elem=sb&src=searchresults&dest_id=-1416701&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=fr&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=54b45ebe8687040b&ac_meta=GhA1NGI0NWViZTg2ODcwNDBiIAAoATICZnI6C2NhcmNhc3Nvbm5lQABKAFAA&group_adults=2&no_rooms=1&group_children=0",
    "Ariege" : "https://www.booking.com/searchresults.fr.html?ss=Ari%C3%A8ge%2C+France&efdco=1&label=gen173nr-10CAEoggI46AdIM1gEaE2IAQGYATO4AQfIAQ_YAQPoAQH4AQGIAgGoAgG4AozwyMcGwAIB0gIkN2ZlNDhmMDQtNTg3Mi00NzI3LWExNWEtZjI4YjNiNDc4YTRh2AIB4AIB&sid=ec92b03eccf337e979d9b3cac5b2d333&aid=304142&lang=fr&sb=1&src_elem=sb&src=searchresults&dest_id=2507&dest_type=region&ac_position=2&ac_click_type=b&ac_langcode=fr&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=e19b5ef0f9ba04ce&ac_meta=GhBlMTliNWVmMGY5YmEwNGNlIAIoATICZnI6BUFyacOoQABKAFAA&group_adults=2&no_rooms=1&group_children=0",
    "Toulouse" : "https://www.booking.com/searchresults.fr.html?ss=Toulouse%2C+Midi-Pyr%C3%A9n%C3%A9es%2C+France&efdco=1&label=gen173nr-10CAEoggI46AdIM1gEaE2IAQGYATO4AQfIAQ_YAQPoAQH4AQGIAgGoAgG4AozwyMcGwAIB0gIkN2ZlNDhmMDQtNTg3Mi00NzI3LWExNWEtZjI4YjNiNDc4YTRh2AIB4AIB&sid=ec92b03eccf337e979d9b3cac5b2d333&aid=304142&lang=fr&sb=1&src_elem=sb&src=searchresults&dest_id=-1473166&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=fr&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=80465f4df81f00d5&ac_meta=GhA4MDQ2NWY0ZGY4MWYwMGQ1IAAoATICZnI6CFRvdWxvdXNlQABKAFAA&group_adults=2&no_rooms=1&group_children=0",
    "Montauban" : "https://www.booking.com/searchresults.fr.html?ss=Montauban%2C+Midi-Pyr%C3%A9n%C3%A9es%2C+France&efdco=1&label=gen173nr-10CAEoggI46AdIM1gEaE2IAQGYATO4AQfIAQ_YAQPoAQH4AQGIAgGoAgG4AozwyMcGwAIB0gIkN2ZlNDhmMDQtNTg3Mi00NzI3LWExNWEtZjI4YjNiNDc4YTRh2AIB4AIB&sid=ec92b03eccf337e979d9b3cac5b2d333&aid=304142&lang=fr&sb=1&src_elem=sb&src=searchresults&dest_id=-1452421&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=fr&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=c62b5f587d860468&ac_meta=GhBjNjJiNWY1ODdkODYwNDY4IAAoATICZnI6CW1vbnRhdWJhbkAASgBQAA%3D%3D&group_adults=2&no_rooms=1&group_children=0",
    "Biarritz" : "https://www.booking.com/searchresults.fr.html?ss=Biarritz%2C+Aquitaine%2C+France&efdco=1&label=gen173nr-10CAEoggI46AdIM1gEaE2IAQGYATO4AQfIAQ_YAQPoAQH4AQGIAgGoAgG4AozwyMcGwAIB0gIkN2ZlNDhmMDQtNTg3Mi00NzI3LWExNWEtZjI4YjNiNDc4YTRh2AIB4AIB&sid=ec92b03eccf337e979d9b3cac5b2d333&aid=304142&lang=fr&sb=1&src_elem=sb&src=searchresults&dest_id=-1412526&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=fr&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=67c45f69d27202ce&ac_meta=GhA2N2M0NWY2OWQyNzIwMmNlIAAoATICZnI6BmJpYXJyaUAASgBQAA%3D%3D&group_adults=2&no_rooms=1&group_children=0",
    "Bayonne" : "https://www.booking.com/searchresults.fr.html?ss=Bayonne%2C+Aquitaine%2C+France&efdco=1&label=gen173nr-10CAEoggI46AdIM1gEaE2IAQGYATO4AQfIAQ_YAQPoAQH4AQGIAgGoAgG4AozwyMcGwAIB0gIkN2ZlNDhmMDQtNTg3Mi00NzI3LWExNWEtZjI4YjNiNDc4YTRh2AIB4AIB&sid=ec92b03eccf337e979d9b3cac5b2d333&aid=304142&lang=fr&sb=1&src_elem=sb&src=searchresults&dest_id=-1410844&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=fr&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=bc625f78768c04c3&ac_meta=GhBiYzYyNWY3ODc2OGMwNGMzIAAoATICZnI6B2JheW9ubmVAAEoAUAA%3D&group_adults=2&no_rooms=1&group_children=0",
    "La Rochelle" : "https://www.booking.com/searchresults.fr.html?ss=La+Rochelle%2C+Poitou-Charentes%2C+France&efdco=1&label=gen173nr-10CAEoggI46AdIM1gEaE2IAQGYATO4AQfIAQ_YAQPoAQH4AQGIAgGoAgG4AozwyMcGwAIB0gIkN2ZlNDhmMDQtNTg3Mi00NzI3LWExNWEtZjI4YjNiNDc4YTRh2AIB4AIB&sid=ec92b03eccf337e979d9b3cac5b2d333&aid=304142&lang=fr&sb=1&src_elem=sb&src=searchresults&dest_id=-1438604&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=fr&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=6fad5f8eb1120e41&ac_meta=GhA2ZmFkNWY4ZWIxMTIwZTQxIAAoATICZnI6C2xhIHJvY2hlbGxlQABKAFAA&group_adults=2&no_rooms=1&group_children=0"
}

In [ ]:
# This did a much better job at scraping Booking.com, ironically

hotels_df_dict = {"placename" : [],
                  "hotel_name" : [],
                  "hotel_bookingdotcom_page" : [],
                  "user_rating" : [],
                  "hotel_lat" : [],
                  "hotel_lon" : [],
                  "description" : []}

for placename, url in urls_dict.items():
    response = Selector(text=requests.get(url).text)
    hotels = response.xpath("//*[contains(@class, 'b071d3eccd afd3558156 ecc7830bbb')]/div[1]/div[1]/div[1]")

    print(f"Got hotels HTML for {placename}\n{hotels.get() is None}")

    for hotel in hotels:
        hotel_url = hotel.xpath("div[1]/a").attrib["href"]
        hotels_df_dict["placename"].append(placename)
        hotels_df_dict["hotel_name"].append(hotel.xpath("div[1]/a/div[1]/h3/div[1]/text()").get())
        hotels_df_dict["hotel_bookingdotcom_page"].append(hotel_url)
        hotels_df_dict["user_rating"].append(float(hotel.xpath("div[2]/div[1]/div[1]/div[2]/text()").get().replace(",", ".")))
        hotels_df_dict["hotel_description"].append(hotel.xpath("div[1]/div[1]/p/text()").get())
        print("Added data to df!")
        sleep(randint(1, 5))
        coordinates_response = Selector(text=requests.get(hotel_url).text)
        try:
            latlon = coordinates_response.xpath("//*[contains(@id, 'map_trigger_header')]")\
                                        .attrib["data-atlas-latlng"]\
                                        .split(",")
        except:
            print(coordinates_response.xpath("/html").get())
        hotels_df_dict["hotel_lat"].append(float(latlon[0]))
        hotels_df_dict["hotel_lon"].append(float(latlon[1]))
        print(latlon)

    sleep(randint(5, 12))

hotels_df = pd.DataFrame(hotels_df_dict)
hotels_df.to_csv("place_hotel2.csv")

Got hotels HTML for Mont Saint Michel
False
Added data to df!
['48.61470048629041', '-1.5096169710159302']
Added data to df!
['48.6175872716489', '-1.51039615273476']
Added data to df!
['48.61538141368341', '-1.510709971189499']
Added data to df!
['48.61424652959294', '-1.510545015335083']
Added data to df!
['48.61626270451236', '-1.510905772447586']
Added data to df!
['48.612937834706464', '-1.5101051330566406']
Added data to df!
['48.63534942564122', '-1.5103787183761597']
Added data to df!
['48.63508531723403', '-1.5105396509170532']
Added data to df!
['48.636022984447116', '-1.509895920753479']
Added data to df!
['48.6354874', '-1.5101555']
Got hotels HTML for St Malo
False
Added data to df!
['48.63112529789551', '-2.010825276374817']
Added data to df!
['48.64961099853388', '-2.024303376674652']
Added data to df!
['48.650727056010815', '-2.0249454730163734']
Added data to df!
['48.638587743159896', '-1.96755051612854']
Added data to df!
['48.6495690720354', '-2.02686496197134']
Added data to df!
['48.63962613573007', '-2.012365314358476']
Added data to df!
['48.63609920237719', '-1.9892066717147827']
Added data to df!
['48.66167887690836', '-1.9916501641273499']
Added data to df!
['48.652105960510724', '-2.0171231031417847']
Added data to df!
['48.649205201142465', '-2.024633288383484']
Got hotels HTML for Bayeux
False
Added data to df!
['49.27232559999999', '-0.6985101000000213']
Added data to df!
['49.27551885808722', '-0.700964480638504']
Added data to df!
['49.27815768633019', '-0.7035139203071594']
Added data to df!
['49.27627832312484', '-0.6983694434165955']
Added data to df!
['49.276031585766006', '-0.7017248868942261']
Added data to df!
['49.27899410241933', '-0.7084169983863831']
Added data to df!
['49.27446149480972', '-0.7079898076568525']
Added data to df!
['49.27933593079586', '-0.7070561004303499']
Added data to df!
['49.27647467688673', '-0.7024700846557153']
Added data to df!
['49.27981023429335', '-0.7106749165699284']
Got hotels HTML for Le Havre
False
Added data to df!
['49.49008699', '0.097746957']
Added data to df!
['49.498238', '0.128837']
Added data to df!
['49.49331760456112', '0.12530688339768403']
Added data to df!
['49.4916414175279', '0.11876016855239868']
Added data to df!
['49.50318944974505', '0.08882135152816772']
Added data to df!
['49.49117449151481', '0.11193662881851196']
Added data to df!
['49.49308920830414', '0.13096153736114502']
Added data to df!
['49.493988', '0.1227326']
Added data to df!
['49.488378', '0.108705']
Added data to df!
['49.49141927977486', '0.10070756077766418']
Got hotels HTML for Rouen
False
Added data to df!
['49.4388505', '1.0899553']
Added data to df!
['49.439067', '1.089627']
Added data to df!
['49.453285640641354', '1.0982852973166501']
Added data to df!
['49.421793', '1.106844']
Added data to df!
['49.446441', '1.09412']
Added data to df!
['49.42498665756126', '1.0686087460327043']
Added data to df!
['49.429988', '1.072398']
Added data to df!
['49.425341', '1.068718']
Added data to df!
['49.43572312061268', '1.1027312278747559']
Added data to df!
['49.4433271352408', '1.0945739597082138']
Got hotels HTML for Paris
False
Added data to df!
['48.82542397136288', '2.382372175254832']
Added data to df!
['48.850212', '2.362765']
Added data to df!
['48.837362', '2.319906']
Added data to df!
['48.867792', '2.303308']
Added data to df!
['48.872866', '2.3165240000000002']
Added data to df!
['48.87368', '2.3520849999999998']
Added data to df!
['48.882529', '2.319161']
Added data to df!
['48.844209', '2.280853']
Added data to df!
['48.83582', '2.292364']
Added data to df!
['48.87192', '2.370044']
Got hotels HTML for Amiens
False
Added data to df!
['49.879612824182246', '2.266651015808119']
Added data to df!
['49.891422', '2.304996']
Added data to df!
['49.891591', '2.313573']
Added data to df!
['49.89448370908586', '2.276802533729551']
Added data to df!
['49.891999', '2.291969999999992']
Added data to df!
['49.891249', '2.30953']
Added data to df!
['49.894445193999786', '2.3009423911571503']
Added data to df!
['49.889778847078894', '2.3024994134902954']
Added data to df!
['49.89167619790575', '2.30775386095047']
Added data to df!
['49.89571084445366', '2.299562394618988']
Got hotels HTML for Lille
False
Added data to df!
['50.645775', '2.9864651']
Added data to df!
['50.6288419', '3.0519791']
Added data to df!
['50.615353999999996', '3.043125']
Added data to df!
['50.634074', '3.064229']
Added data to df!
['50.627831', '3.063592']
Added data to df!
['50.639065', '3.070951']
Added data to df!
['50.6397393', '3.067428100000029']
Added data to df!
['50.633198486768755', '3.074476813491856']
Added data to df!
['50.6456982973099', '3.072109669446945']
Added data to df!
['50.63430829317451', '3.061618208885193']
Got hotels HTML for Strasbourg
False
Added data to df!
['48.585942', '7.747235']
Added data to df!
['48.577043189133', '7.742526903748512']
Added data to df!
['48.58052972845092', '7.74373322725296']
Added data to df!
['48.58383632696426', '7.734948992729187']
Added data to df!
['48.60808508242673', '7.800015360116959']
Added data to df!
['48.57934881136194', '7.751557230949402']
Added data to df!
['48.58999292620854', '7.75154247879982']
Added data to df!
['48.582535', '7.7538277']
Added data to df!
['48.59900335', '7.761959941']
Added data to df!
['48.591522', '7.754599']
Got hotels HTML for Chateau du Haut Koenigsbourg
False
Added data to df!
['48.22489193155129', '7.353954797553229']
Added data to df!
['48.271757028793665', '7.399505420901505']
Added data to df!
['48.25704493794585', '7.419126927852631']
Added data to df!
['48.13857095291248', '7.265514135360718']
Added data to df!
['48.370512', '7.28776']
Added data to df!
['48.29164897859645', '7.424096122090077']
Got hotels HTML for Colmar
False
Added data to df!
['48.07545713654288', '7.353532165288925']
Added data to df!
['48.07859549360517', '7.3555270582437515']
Added data to df!
['48.07161741558895', '7.3599910552253505']
Added data to df!
['48.0963028332922', '7.36164164047545']
Added data to df!
['48.09922', '7.3627839999999996']
Added data to df!
['48.079198', '7.363507']
Added data to df!
['48.086015232964435', '7.357299327850342']
Added data to df!
['48.11283258340826', '7.365206480026245']
Added data to df!
['48.07654046258575', '7.349873632192612']
Added data to df!
['48.07623849558461', '7.356447726488113']
Got hotels HTML for Eguisheim
False
Added data to df!
['48.043271326244984', '7.3041218519210815']
Added data to df!
['48.04242042576413', '7.306319251656532']
Added data to df!
['48.042238408346414', '7.309167757630348']
Added data to df!
['48.04228862011209', '7.309451401233673']
Added data to df!
['48.0349876742797', '7.27613836526871']
Added data to df!
['48.0421578072359', '7.30737026134227']
Added data to df!
['48.0418675', '7.3053691']
Added data to df!
['48.045389099073', '7.301809369312']
Added data to df!
['48.0424804', '7.306616099999999']
Added data to df!
['48.07545713654288', '7.353532165288925']
Got hotels HTML for Besancon
False
Added data to df!
['47.2801612', '5.9877459']
Added data to df!
['47.23547525170847', '5.9000853988113455']
Added data to df!
['47.24045605146395', '6.025995332734055']
Added data to df!
['47.23856536577556', '6.025325059890747']
Added data to df!
['47.23171766809705', '6.027591526508331']
Added data to df!
['47.22448655881508', '5.9561240673065186']
Added data to df!
['47.25435722578138', '5.995480120182037']
Added data to df!
['47.23727602649555', '6.02586954832077']
Added data to df!
['47.23154100035795', '6.026580333709717']
Added data to df!
['47.246146', '6.033186']
Got hotels HTML for Dijon
False
Added data to df!
['47.32359832', '5.037261159']
Added data to df!
['47.3245398', '5.0276148']
Added data to df!
['47.272895', '5.047662']
Added data to df!
['47.322315', '5.034377']
Added data to df!
['47.361115', '5.05172']
Added data to df!
['47.322817066024044', '5.036885317790961']
Added data to df!
['47.32428953092841', '5.034272273016313']
Added data to df!
['47.360673', '5.049352999999996']
Added data to df!
['47.326514088300485', '5.033579617738724']
Added data to df!
['47.3158501277018', '5.04426687955856']
Got hotels HTML for Annecy
False
Added data to df!
['45.892319', '6.0895437']
Added data to df!
['45.899053', '6.124137']
Added data to df!
['45.897015', '6.131543']
Added data to df!
['45.905699', '6.151953']
Added data to df!
['45.9183227', '6.15250679999997']
Added data to df!
['45.89771606659', '6.13013094662711']
Added data to df!
['45.90041837042851', '6.120344504670356']
Added data to df!
['45.898238796612006', '6.12250953912735']
Added data to df!
['45.905514493453836', '6.144128143787384']
Added data to df!
['45.90393736458728', '6.119993627071381']
Got hotels HTML for Grenoble
False
Added data to df!
['45.186911', '5.731293']
Added data to df!
['45.18495018003908', '5.72598980937039']
Added data to df!
['45.190815035100044', '5.728548020124435']
Added data to df!
['45.19079329686088', '5.716696679592133']
Added data to df!
['45.19035711261138', '5.727330967783928']
Added data to df!
['45.18920402005693', '5.725372284650803']
Added data to df!
['45.189522', '5.716226000000006']
Added data to df!
['45.18410130511121', '5.732948184013367']
Added data to df!
['45.1910782561633', '5.715598315000534']
Added data to df!
['45.18928483181276', '5.7186198234558105']
Got hotels HTML for Lyon
False
Added data to df!
['45.760402581312896', '4.85792056375427']
Added data to df!
['45.758649', '4.836915']
Added data to df!
['45.74439127455862', '4.892542362213135']
Added data to df!
['45.759217144079', '4.82313535390313']
Added data to df!
['45.76314438789889', '4.825807996094227']
Added data to df!
['45.7632849132656', '4.827415645122528']
Added data to df!
['45.74885', '4.863691']
Added data to df!
['45.78235', '4.83378']
Added data to df!
['45.725243', '4.830177']
Added data to df!
['45.742544', '4.82128']
Got hotels HTML for Gorges du Verdon
False
Added data to df!
['43.6990888705541', '6.0372394323349']
Added data to df!
['43.73278619599797', '6.161522269248962']
Added data to df!
['43.846625749126176', '6.513554155826569']
Added data to df!
['43.843437772077586', '6.221673488616943']
Added data to df!
['43.760622', '5.888973999999962']
Added data to df!
['43.758087', '5.890188']
Added data to df!
['43.756056', '6.140723']
Added data to df!
['43.778980122502865', '6.341233491930325']
Added data to df!
['43.75062074681262', '6.321302587890614']
Added data to df!
['43.84593903303046', '6.512846052646637']
Got hotels HTML for Bormes les Mimosas
False
Added data to df!
['43.14893353509435', '6.303266286849976']
Added data to df!
['43.144568554121996', '6.351684182882309']
Added data to df!
['43.152872', '6.342654']
Added data to df!
['43.12549', '6.357300000000009']
Added data to df!
['43.15187759303926', '6.343135982751846']
Added data to df!
['43.144264665268814', '6.353165855155942']
Added data to df!
['43.142501', '6.3491788']
Added data to df!
['43.150652', '6.3411229']
Added data to df!
['43.12241551445', '6.359347321328']
Added data to df!
['43.124079792347', '6.351798812714']
Got hotels HTML for Cassis
False
Added data to df!
['43.216440236856805', '5.541745724536895']
Added data to df!
['43.21457326278473', '5.540146976709366']
Added data to df!
['43.221840494518375', '5.543384896958969']
Added data to df!
['43.211337', '5.529502']
Added data to df!
['43.21403', '5.53859']
Added data to df!
['43.234829299000964', '5.511910519238427']
Added data to df!
['43.213349460527084', '5.531262829899788']
Added data to df!
['43.21522996680949', '5.533696934580803']
Added data to df!
['43.21622493056339', '5.542900264263153']
Added data to df!
['43.213706213836964', '5.538958087563515']
Got hotels HTML for Marseille
False
Added data to df!
['43.2920868', '5.389204']
Added data to df!
['43.239497', '5.406246499999952']
Added data to df!
['43.28282806447971', '5.387259051203728']
Added data to df!
['43.3101149', '5.3703396']
Added data to df!
['43.31327', '5.40482']
Added data to df!
['43.288782', '5.378967']
Added data to df!
['43.30574814984538', '5.371058398811321']
Added data to df!
['43.247273', '5.3904309999999995']
Added data to df!
['43.296986', '5.379321']
Added data to df!
['43.3024211', '5.36863370000003']
Got hotels HTML for Aix en Provence
False
Added data to df!
['43.56879', '5.47851']
Added data to df!
['43.523068', '5.457699']
Added data to df!
['43.5247755', '5.45022449999999']
Added data to df!
['43.52116980487331', '5.4965972900390625']
Added data to df!
['43.51886697166336', '5.4416146874427795']
Added data to df!
['43.536101030690894', '5.448788137561678']
Added data to df!
['43.52468223421984', '5.450389534235001']
Added data to df!
['43.5205148', '5.4471929']
Added data to df!
['43.49196900747259', '5.371623']
Added data to df!
['43.5255987', '5.45172079999998']
Got hotels HTML for Avignon
False
Added data to df!
['43.9474236', '4.8079036']
Added data to df!
['43.949637766959796', '4.806358963251114']
Added data to df!
['43.944616324685065', '4.8006123304367065']
Added data to df!
['43.94930610704683', '4.809345602989197']
Added data to df!
['43.92929', '4.784118000000035']
Added data to df!
['43.944032127814744', '4.80533167719841']
Added data to df!
['43.943629463158565', '4.812171310186386']
Added data to df!
['43.922757658189205', '4.804295003414154']
Added data to df!
['43.92616548476504', '4.844420850276947']
Added data to df!
['43.94290137673605', '4.7980427742004395']
Got hotels HTML for Uzes
False
Added data to df!
['44.023394710582856', '4.419290721416473']
Added data to df!
['44.01246437098573', '4.421800111045059']
Added data to df!
['44.0127444719537', '4.42113071680069']
Added data to df!
['44.00284484835363', '4.416452050099906']
Added data to df!
['44.02843142473164', '4.420023858328932']
Added data to df!
['44.0114872', '4.4198868000000004']
Added data to df!
['44.0108258', '4.4177601']
Added data to df!
['44.011246', '4.418813']
Added data to df!
['44.0096647', '4.4180397']
Added data to df!
['44.0136116', '4.4213639']
Got hotels HTML for Nimes
False
Added data to df!
['43.83866612768399', '4.352767914533615']
Added data to df!
['43.837117', '4.357898']
Added data to df!
['43.83470575029483', '4.36731219291687']
Added data to df!
['43.8281614', '4.354790200000025']
Added data to df!
['43.832055902146784', '4.3673644959926605']
Added data to df!
['43.83175754591007', '4.36697356402874']
Added data to df!
['43.83959475654075', '4.3610841035842896']
Added data to df!
['43.81389058589602', '4.34434175491333']
Added data to df!
['43.83249328044521', '4.367856681346893']
Added data to df!
['43.83881509620307', '4.3548184633255005']
Got hotels HTML for Aigues Mortes
False
Added data to df!
['43.56498661964503', '4.191751956841472']
Added data to df!
['43.568035521418736', '4.190343797190508']
Added data to df!
['43.57186625316511', '4.19366168974193']
Added data to df!
['43.572987520084624', '4.194824695587158']
Added data to df!
['43.5689974', '4.18829819999996']
Added data to df!
['43.56651350885335', '4.191158152149569']
Added data to df!
['43.57702546263962', '4.1975390911102295']
Added data to df!
['43.568085130564', '4.193533346966']
Added data to df!
['43.5661556', '4.1923449999999995']
Added data to df!
['43.566227', '4.191121']
Got hotels HTML for Saintes Maries de la mer
False
Added data to df!
['43.45687142239208', '4.426175951957703']
Added data to df!
['43.46575555626723', '4.413934350013733']
Added data to df!
['43.4551249427373', '4.42874014377594']
Added data to df!
['43.451133', '4.430953']
Added data to df!
['43.452330859800156', '4.433649927377701']
Added data to df!
['43.4726010948223', '4.410120248794556']
Added data to df!
['43.45106617843045', '4.4250936806201935']
Added data to df!
['43.46095607974298', '4.422318935394287']
Added data to df!
['43.47145265577682', '4.401826858520508']
Added data to df!
['43.45262779808949', '4.430766552686691']
Got hotels HTML for Collioure
False
Added data to df!
['42.5288828', '3.0793938']
Added data to df!
['42.52534777273077', '3.0903244632682725']
Added data to df!
['42.5261673320343', '3.082355707883835']
Added data to df!
['42.52538158720205', '3.082563914358616']
Added data to df!
['42.525914313393564', '3.0826815962791443']
Added data to df!
['42.53378310875555', '3.064337968826294']
Added data to df!
['42.52417280573015', '3.0893106758594513']
Added data to df!
['42.524114491069405', '3.0893656611442566']
Added data to df!
['42.52371617082933', '3.0871347337961197']
Added data to df!
['42.526851', '3.083962']
Got hotels HTML for Carcassonne
False
Added data to df!
['43.206838', '2.382095']
Added data to df!
['43.20136837496012', '2.3602621257305145']
Added data to df!
['43.227146962271064', '2.3963995277881622']
Added data to df!
['43.191770313736136', '2.3346805572509766']
Added data to df!
['43.207746', '2.366914']
Added data to df!
['43.21085', '2.357769']
Added data to df!
['43.21103244477474', '2.3581999522190245']
Added data to df!
['43.207957833138664', '2.312631458044052']
Added data to df!
['43.2077994786468', '2.3673471808433533']
Added data to df!
['43.20925202357567', '2.3867475986480713']
Got hotels HTML for Ariege
False
Added data to df!
['43.12481697810204', '1.6023459630431969']
Added data to df!
['43.09194', '1.778273']
Added data to df!
['42.722361', '1.839916']
Added data to df!
['42.71983699138773', '1.8418669243980048']
Added data to df!
['43.00523949646403', '1.6147595643997192']
Added data to df!
['42.721329', '1.839279']
Added data to df!
['42.84528016217312', '1.7411398887634277']
Added data to df!
['42.97737629547595', '1.146247386932373']
Added data to df!
['42.965632378261084', '1.6089418530464172']
Added data to df!
['42.84354286372162', '1.601606011390686']
Got hotels HTML for Toulouse
False
Added data to df!
['43.5843376998005', '1.49191968227842']
Added data to df!
['43.601635423984', '1.407013156361']
Added data to df!
['43.60536', '1.438261']
Added data to df!
['43.6084843', '1.4534278']
Added data to df!
['43.610053', '1.43037']
Added data to df!
['43.605414', '1.449934']
Added data to df!
['43.584778', '1.491708000000017']
Added data to df!
['43.6100905', '1.4530465999999933']
Added data to df!
['43.60043698506804', '1.443997398018837']
Added data to df!
['43.60490588615922', '1.4431337267160416']
Got hotels HTML for Montauban
False
Added data to df!
['44.015742070285896', '1.354912519454956']
Added data to df!
['44.020995559797', '1.349240014017']
Added data to df!
['43.9362872066926', '1.32209782791136']
Added data to df!
['43.990284', '1.338824']
Added data to df!
['44.040119650175065', '1.3860239000000547']
Added data to df!
['44.01542572857878', '1.3540729880332947']
Added data to df!
['43.980810842951904', '1.330394446849823']
Added data to df!
['44.020542927203735', '1.3495668768882751']
Added data to df!
['44.00526', '1.383153']
Added data to df!
['44.0894414091139', '1.34851889310085']
Got hotels HTML for Biarritz
False
Added data to df!
['43.480133535313925', '-1.5607613325119019']
Added data to df!
['43.490592', '-1.5516969999999999']
Added data to df!
['43.482133269718496', '-1.567530557513237']
Added data to df!
['43.48106772604739', '-1.5632075071334839']
Added data to df!
['43.48218970895052', '-1.5663591027259827']
Added data to df!
['43.479203222687474', '-1.5622150897979736']
Added data to df!
['43.482718094375606', '-1.5613406896591187']
Added data to df!
['43.479138995554955', '-1.5622754395008087']
Added data to df!
['43.48643904244932', '-1.5562176704406738']
Added data to df!
['43.481694404236', '-1.5630841255187988']
Got hotels HTML for Bayonne
False
Added data to df!
['43.482321', '-1.468164']
Added data to df!
['43.492371', '-1.472588']
Added data to df!
['43.49534430000001', '-1.4825117999999975']
Added data to df!
['43.485026198989566', '-1.4753705263137817']
Added data to df!
['43.49349108918729', '-1.4526334404945374']
Added data to df!
['43.49618306480432', '-1.4696010947227478']
Added data to df!
['43.495405741197395', '-1.4708241820335388']
Added data to df!

In [85]:
hotels_df.head(20)

,placename,hotel_name,hotel_bookingdotcom_page,user_rating,hotel_lat,hotel_lon,description
0,Mont Saint Michel,Hôtel Vert,https://www.booking.com/hotel/fr/vert.fr.html,"8,1",48.614700,-1.509617,L’Hotel Vert vous propose des chambres décorée...
1,Mont Saint Michel,Le Relais Saint Michel,https://www.booking.com/hotel/fr/le-relais-sai...,"8,2",48.617587,-1.510396,Le Relais Saint Michel vous accueille face à l...
2,Mont Saint Michel,Hotel Gabriel,https://www.booking.com/hotel/fr/hotel-gabriel...,"8,3",48.615381,-1.510710,Hotel Gabriel is located 1.6 Km from Mont Sain...
3,Mont Saint Michel,Mercure Mont Saint Michel,https://www.booking.com/hotel/fr/mont-saint-mi...,"8,3",48.614247,-1.510545,Installé dans des espaces verts à seulement 2 ...
4,Mont Saint Michel,Le Relais Du Roy,https://www.booking.com/hotel/fr/le-relais-du-...,"8,3",48.616263,-1.510906,Le Relais Du Roy est un hôtel 3 étoiles situé ...
5,Mont Saint Michel,Le Saint Aubert,https://www.booking.com/hotel/fr/hotel-saint-a...,"7,6",48.612938,-1.510105,"Niché dans un écrin de verdure, à seulement 2 ..."
6,Mont Saint Michel,Les Terrasses Poulard,https://www.booking.com/hotel/fr/les-terrasses...,"7,3",48.635349,-1.510379,Occupant 2 bâtiments différents au cœur du Mon...
7,Mont Saint Michel,La Mère Poulard,https://www.booking.com/hotel/fr/la-mere-poula...,"7,6",48.635085,-1.510540,Séjournez dans un hôtel historique au cœur du ...
8,Mont Saint Michel,Le Mouton Blanc,https://www.booking.com/hotel/fr/le-mouton-bla...,"7,2",48.636023,-1.509896,"Situé au pied de l’abbaye, l’hôtel Le Mouton B..."
9,Mont Saint Michel,Appart Standing - La Coque d'Or,https://www.booking.com/hotel/fr/la-coque-d-or...,"9,6",48.635487,-1.510155,L’hébergement Appart Standing - La Coque d'Or ...
10,St Malo,L'Hôtel Particulier Ascott,https://www.booking.com/hotel/fr/ascott.fr.html,"9,2",48.631125,-2.010825,"Entièrement rénové, l'établissement L'Hôtel Pa..."
11,St Malo,Hôtel Bristol Union Intra Muros,https://www.booking.com/hotel/fr/bristol-union...,"9,1",48.649611,-2.024303,L’Hôtel Bristol Union Intra Muros est situé au...
12,St Malo,Hôtel Le Nautilus,https://www.booking.com/hotel/fr/le-nautilus.f...,"9,4",48.650727,-2.024945,L’Hôtel Le Nautilus occupe un bâtiment rénové ...
13,St Malo,Château Hôtel Du Colombier,https://www.booking.com/hotel/fr/chateau-du-co...,"9,1",48.638588,-1.967551,Niché au cœur d'un parc de 6 hectares à seulem...
14,St Malo,Golden Tulip Saint Malo– Le Grand Bé,https://www.booking.com/hotel/fr/golden-tulip-...,"8,6",48.649569,-2.026865,Le Golden Tulip Saint Malo– Le Grand Bé est si...
15,St Malo,ibis Styles Saint Malo Port,https://www.booking.com/hotel/fr/ibis-styles-s...,"8,3",48.639626,-2.012365,Doté d'un snack-bar et d'une connexion Wi-Fi g...
16,St Malo,Kyriad Prestige Saint-Malo,https://www.booking.com/hotel/fr/kyriad-presti...,"8,8",48.636099,-1.989207,Le Kyriad Prestige Saint-Malo se trouve à 4 km...
17,St Malo,Hôtel Ar Iniz,https://www.booking.com/hotel/fr/ar-iniz.fr.html,"8,6",48.661679,-1.991650,"Providing a direct access to the Sillon Beach,..."
18,St Malo,Hôtel L'Adresse - Entièrement rénové,https://www.booking.com/hotel/fr/adresse.fr.html,"8,8",48.652106,-2.017123,L’Hôtel L'Adresse propose un hébergement indép...
19,St Malo,La Maison des Armateurs,https://www.booking.com/hotel/fr/la-maison-des...,"8,8",48.649205,-2.024633,"Situé dans le centre historique de Saint-Malo,..."

In [ ]:
full_df = pd.merge(left=pd.read_csv("place_hotel.csv", index_col="Unnamed: 0"),
                   right=pd.read_csv("place_weather.csv", index_col="Unnamed: 0"),
                   how="left",
                   on="placename")
full_df.head()

,Unnamed: 0,placename,hotel_name,hotel_bookingdotcom_page,user_rating,hotel_lat,hotel_lon,hotel_description,place_id,POI_lon,POI_lat,mean_max_temp_over_next_7_days,mean_cloud_cover_over_next_7_days,mean_POP_over_next_7_days,bad_weather_score
0,0,Mont Saint Michel,Hôtel Vert,https://www.booking.com/hotel/fr/vert.fr.html,8.1,48.614700,-1.509617,L’Hotel Vert vous propose des chambres décorée...,msm,-1.51146,48.635954,18.3325,51.875,18.3325,36.366389
1,1,Mont Saint Michel,Le Relais Saint Michel,https://www.booking.com/hotel/fr/le-relais-sai...,8.2,48.617587,-1.510396,Le Relais Saint Michel vous accueille face à l...,msm,-1.51146,48.635954,18.3325,51.875,18.3325,36.366389
2,2,Mont Saint Michel,Hotel Gabriel,https://www.booking.com/hotel/fr/hotel-gabriel...,8.3,48.615381,-1.510710,Hotel Gabriel is located 1.6 Km from Mont Sain...,msm,-1.51146,48.635954,18.3325,51.875,18.3325,36.366389
3,3,Mont Saint Michel,Mercure Mont Saint Michel,https://www.booking.com/hotel/fr/mont-saint-mi...,8.3,48.614247,-1.510545,Installé dans des espaces verts à seulement 2 ...,msm,-1.51146,48.635954,18.3325,51.875,18.3325,36.366389
4,4,Mont Saint Michel,Le Relais Du Roy,https://www.booking.com/hotel/fr/le-relais-du-...,8.3,48.616263,-1.510906,Le Relais Du Roy est un hôtel 3 étoiles situé ...,msm,-1.51146,48.635954,18.3325,51.875,18.3325,36.366389

## Loading the CSV Into an S3 Bucket

In [17]:
load_dotenv()

session = boto3.Session(aws_access_key_id=os.environ["AWS_ACCESS_KEY_ID"],
                        aws_secret_access_key=os.environ["AWS_SECRET_ACCESS_KEY"])
s3 = session.resource("s3")
bucket = s3.create_bucket(Bucket="jedha-kayak-cert",
                          CreateBucketConfiguration={"LocationConstraint": "eu-west-3"}) 
bucket.upload_file("full_data.csv", "full_data.csv")

## Making the Final Visualisations

In [ ]:
df = pd.read_csv("full_data.csv")

In [4]:
df.head()

,Unnamed: 0,placename,hotel_name,hotel_bookingdotcom_page,user_rating,hotel_lat,hotel_lon,hotel_description,place_id,POI_lon,POI_lat,mean_max_temp_over_next_7_days,mean_cloud_cover_over_next_7_days,mean_POP_over_next_7_days,bad_weather_score
0,0,Mont Saint Michel,Hôtel Vert,https://www.booking.com/hotel/fr/vert.fr.html,8.1,48.614700,-1.509617,L’Hotel Vert vous propose des chambres décorée...,msm,-1.51146,48.635954,18.3325,51.875,18.3325,36.366389
1,1,Mont Saint Michel,Le Relais Saint Michel,https://www.booking.com/hotel/fr/le-relais-sai...,8.2,48.617587,-1.510396,Le Relais Saint Michel vous accueille face à l...,msm,-1.51146,48.635954,18.3325,51.875,18.3325,36.366389
2,2,Mont Saint Michel,Hotel Gabriel,https://www.booking.com/hotel/fr/hotel-gabriel...,8.3,48.615381,-1.510710,Hotel Gabriel is located 1.6 Km from Mont Sain...,msm,-1.51146,48.635954,18.3325,51.875,18.3325,36.366389
3,3,Mont Saint Michel,Mercure Mont Saint Michel,https://www.booking.com/hotel/fr/mont-saint-mi...,8.3,48.614247,-1.510545,Installé dans des espaces verts à seulement 2 ...,msm,-1.51146,48.635954,18.3325,51.875,18.3325,36.366389
4,4,Mont Saint Michel,Le Relais Du Roy,https://www.booking.com/hotel/fr/le-relais-du-...,8.3,48.616263,-1.510906,Le Relais Du Roy est un hôtel 3 étoiles situé ...,msm,-1.51146,48.635954,18.3325,51.875,18.3325,36.366389

In [ ]:
top_5_destinations_df = df.groupby("placename", as_index=False)[["bad_weather_score", "POI_lon", "POI_lat"]]\
                       .mean()\
                       .sort_values(by="bad_weather_score", ascending=True)\
                       .drop(columns="bad_weather_score")\
                       .head()\
                       .reset_index(drop=True)

top_5_destinations_df

            placename   POI_lon    POI_lat
0     Aix en Provence  5.447474  43.529842
1           Marseille  5.369953  43.296174
2             Avignon  4.805901  43.949249
3              Cassis  5.539632  43.214036
4  Bormes les Mimosas  6.341928  43.150697

In [82]:
fig = px.scatter_map(data_frame=top_5_destinations_df,
                     lon="POI_lon",
                     lat="POI_lat",
                     zoom=7,
                     width=800,
                     height=600,
                     size_max=15,
                     size=[15]*len(top_5_destinations_df),
                     title="The Top 5 Destinations in the Data in Terms of Weather",
                     hover_name="placename")
fig.write_html("top_5_destinations.html")
fig.show()

In [ ]:
top_20_hotels_df = (df[df.placename.isin(top_5_destinations_df.placename.to_list())].sort_values(by="user_rating", ascending=False)\
                                                                        .head(20))

num_rows, num_cols = 3, 2

specs = [[{"type": "scattermap"} for _ in range(num_cols)]
         for _ in range(num_rows)]

fig = make_subplots(rows=num_rows,
                    cols=num_cols,
                    specs=specs)

for index, placename in enumerate(top_5_destinations_df.placename.to_list()):
    subset_df = top_20_hotels_df[top_20_hotels_df.placename == placename]
    
    lon = subset_df.hotel_lon
    lat = subset_df.hotel_lat
    
    fig.add_trace(go.Scattermap(lon=lon,
                                lat=lat,
                                mode="markers",
                                marker=dict(size=10, opacity=0.5),
                                text=subset_df.hotel_name,
                                name=placename
                                ), row=(index // num_cols) + 1,
                                   col=(index % num_cols) + 1)
    map_name = f"map{index + 1}"
    fig.update_layout({map_name : dict(center={"lon" : np.mean(lon),
                                              "lat" : np.mean(lat)},
                                      zoom=10)})

fig.update_layout(height=1000,
                  width=1500,
                  title_text="The Top 20 Hotels in the Data in Terms of Weather and User Ratings")
fig.write_html("top_20_hotels.html")
fig.show()